### ISSUE TITLE
Error writing tests that use connectivity_plus onConnectivityChanged() with cirrusci Docker image for Flutter 2.8.0

### ISSUE THREAD

**Issue by jblough** [fluttercommunity/plus_plugins#650] opened 2021-12-13 12:10 UTC
## System info

Issue occurs on: tests
Plugin name: connectivity_plus
Plugin version: 2.1.0
Flutter doctor output:

```
[✓] Flutter (Channel unknown, 2.8.0, on Ubuntu 20.04.3 LTS 5.10.76-linuxkit, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[!] Android Studio (not installed)
[!] Connected device
    ! No devices available
```

## Steps to Reproduce

Here are the steps that I followed that worked when running with the cirrusci/flutter:2.5.3 image, but failed with the cirrusci/flutter:2.8.0 image

Create a test named connectivity_test.dart with the contents
```
import 'package:connectivity_plus/connectivity_plus.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  test('test something', () async {
    Connectivity().onConnectivityChanged.listen((result) {});

    expect(2 + 2, 4);
  });
}
```

Run the tests with Dockerfile with the contents
```
FROM cirrusci/flutter:2.8.0
COPY . /tmp
WORKDIR /tmp
CMD flutter pub get && flutter test test/connectivity_test.dart
```

I was testing with the command line
`docker build . -t flutter-test && docker run flutter-test`

If the Dockerfile FROM line is changed to `FROM cirrusci/flutter:2.5.3` then the tests run successfully

## Logs

The output from running the tests was
```
Running "flutter pub get" in tmp...                                 4.4s
00:11 +0 -1: test something [E]
  SocketException: Connection failed (OS Error: No such file or directory, errno = 2), address = /var/run/dbus/system_bus_socket, port = 0
  dart:io                                                      Socket.connect
  package:dbus/src/dbus_client.dart 787:28                     DBusClient._openSocket
  package:dbus/src/dbus_client.dart 806:11                     DBusClient._connect
  package:dbus/src/dbus_client.dart 627:11                     DBusClient.callMethod
  package:dbus/src/dbus_client.dart 459:22                     DBusClient.getNameOwner
  package:dbus/src/dbus_client.dart 644:28                     DBusClient._findUniqueName
  package:dbus/src/dbus_client.dart 132:15                     DBusSignalStream._onListen
  dart:async                                                   _StreamImpl.listen
  package:dbus/src/dbus_client.dart 126:31                     DBusSignalStream.listen
  dart:async                                                   _ForwardingStream.listen
  package:nm/src/network_manager_client.dart 2216:48           NetworkManagerClient.connect
  package:connectivity_plus_linux/src/connectivity.dart 58:20  ConnectivityLinux._startListenConnectivity
  dart:async                                                   _StreamImpl.listen
  test/connectivity_test.dart 8:42                             main.<fn>
  test/connectivity_test.dart 7:26                             main.<fn>
  ===== asynchronous gap ===========================
  dart:io                                                      Socket.connect
  package:dbus/src/dbus_client.dart 787:28                     DBusClient._openSocket
  package:dbus/src/dbus_client.dart 806:11                     DBusClient._connect
  package:dbus/src/dbus_client.dart 627:11                     DBusClient.callMethod
  package:dbus/src/dbus_client.dart 459:22                     DBusClient.getNameOwner
  package:dbus/src/dbus_client.dart 644:28                     DBusClient._findUniqueName
  package:dbus/src/dbus_client.dart 132:15                     DBusSignalStream._onListen
  dart:async                                                   _StreamImpl.listen
  package:dbus/src/dbus_client.dart 126:31                     DBusSignalStream.listen
  dart:async                                                   _ForwardingStream.listen
  package:nm/src/network_manager_client.dart 2216:48           NetworkManagerClient.connect
  package:connectivity_plus_linux/src/connectivity.dart 58:20  ConnectivityLinux._startListenConnectivity
  dart:async                                                   _StreamImpl.listen
  test/connectivity_test.dart 8:42                             main.<fn>
  test/connectivity_test.dart 7:26                             main.<fn>

00:12 +0 -1: Some tests failed.
```

flutter analyze output:
```
Analyzing tmp...
No issues found! (ran in 19.1s)
```

flutter doctor -v output:
```
[✓] Flutter (Channel unknown, 2.8.0, on Ubuntu 20.04.3 LTS 5.10.76-linuxkit, locale en_US.UTF-8)
    • Flutter version 2.8.0 at /sdks/flutter
    • Upstream repository unknown
    • Framework revision cf44000065 (5 days ago), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /opt/android-sdk-linux
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /opt/android-sdk-linux
    • ANDROID_SDK_ROOT = /opt/android-sdk-linux
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.20.04)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.
```

**Comment by jpnurmi** [comment] 2022-01-06 17:45
Duplicate of #602.

**Closed by jpnurmi** 2022-01-06 17:45 UTC
Labels: bug
