### ISSUE TITLE
 connectivity_plus use flutter 3.10.0

### ISSUE THREAD

**Issue by bdtask9900** [fluttercommunity/plus_plugins#1814] opened 2023-05-15 04:14 UTC
### Platform

Ios

### Plugin

connectivity_plus

### Version

4.00

### Flutter SDK

3.10.0

### Steps to reproduce

Error (Xcode): File not found: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/arc/libarclite_iphonesimulator.a

Error (Xcode): Linker command failed with exit code 1 (use -v to see invocation)

Could not build the application for the simulator.
Error launching application on iPhone 14 Pro.

### Code Sample

```dart
connectivity_plus: ^4.0.0
```

### Logs

```shell
HEADERMAP_INCLUDES_PROJECT_HEADERS = YES
                        HEADERMAP_USES_FRAMEWORK_PREFIX_ENTRIES = YES
                        HEADERMAP_USES_VFS = YES
                        HEADER_SEARCH_PATHS =
                        "/Users/bdtask/Desktop/mostafiz9900/project_bitbuket/sebaghar_flutter/build/ios/Release-iphonesimulator/ReachabilitySwift/Reachabili
                        ty.framework/Headers"
                        "/Users/bdtask/Desktop/mostafiz9900/project_bitbuket/sebaghar_flutter/build/ios/Release-iphonesimulator/connectivity_plus/connectivi
                        ty_plus.framework/Headers"
                        "/Users/bdtask/Desktop/mostafiz9900/project_bitbuket/sebaghar_flutter/build/ios/Release-iphonesimulator/flutter_statusbarcolor_ns/fl
                        utter_statusbarcolor_ns.framework/Headers"
                        "/Users/bdtask/Desktop/mostafiz9900/project_bitbuket/sebaghar_flutter/build/ios/Release-iphonesimulator/path_provider_foundation/pat
                        h_provider_foundation.framework/Headers"
                        "/Users/bdtask/Desktop/mostafiz9900/project_bitbuket/sebaghar_flutter/build/ios/Release-iphonesimulator/shared_preferences_foundatio
                        n/shared_preferences_foundation.framework/Headers"
                        "/Users/bdtask/Desktop/mostafiz9900/project_bitbuket/sebaghar_flutter/build/ios/Release-iphonesimulator/video_player_avfoundation/vi
                        deo_player_avfoundation.framework/Headers"
                        "/Users/bdtask/Desktop/mostafiz9900/project_bitbuket/sebaghar_flutter/build/ios/Release-iphonesimulator/wakelock/wakelock.framework/
                        Headers"
                        HIDE_BITCODE_SYMBOLS = YES
                        HOME = /Users/bdtask
                        ICONV = /usr/bin/iconv
                        INFOPLIST_EXPAND_BUILD_SETTINGS = YES
                        INFOPLIST_FILE = Target Support Files/Pods-RunnerTests/Pods-RunnerTests-Info.plist
                        INFOPLIST_OUTPUT_FORMAT = binary
                        INFOPLIST_PATH = Pods_RunnerTests.framework/Info.plist
                        INFOPLIST_PREPROCESS = NO
                        INFOSTRINGS_PATH = Pods_RunnerTests.framework/en.lproj/InfoPlist.strings
                        INLINE_PRIVATE_FRAMEWORKS = NO
                        INSTALLHDRS_COPY_PHASE = NO
                        INSTALLHDRS_SCRIPT_PHASE = NO
                        INSTALL_DIR = /tmp/Pods.dst/Library/Frameworks
                        INSTALL_GROUP = staff
                        INSTALL_MODE_FLAG = u+w,go-w,a+rX
                        INSTALL_OWNER = bdtask
                        INSTALL_PATH = /Library/Frameworks
                        INSTALL_ROOT = /tmp/Pods.dst
                        IPHONEOS_DEPLOYMENT_TARGET = 13.0
                        JAVAC_DEFAULT_FLAGS = -J-Xms64m -J-XX:NewSize=4M -J-Dfile.encoding=UTF8
                        JAVA_APP_STUB = /System/Library/Frameworks/JavaVM.framework/Resources/MacOS/JavaApplicationStub
                        JAVA_ARCHIVE_CLASSES = YES
                        JAVA_ARCHIVE_TYPE = JAR
                        JAVA_COMPILER = /usr/bin/javac
                        JAVA_FOLDER_PATH = Pods_RunnerTests.framework/Java
                        JAVA_FRAMEWORK_RESOURCES_DIRS = Resources
                        JAVA_JAR_FLAGS = cv
                        JAVA_SOURCE_SUBDIR = .
                        JAVA_USE_DEPENDENCIES = YES
                        JAVA_ZIP_FLAGS = -urg
                        JIKES_DEFAULT_FLAGS = +E +OLDCSO
                        KEEP_PRIVATE_EXTERNS = NO
                        LD_DEPENDENCY_INFO_FILE =
                        /Users/bdtask/Desktop/mostafiz9900/project_bitbuket/sebaghar_flutter/build/ios/Pods.build/Release-iphonesimulator/Pods-RunnerTests.b
                        uild/Objects-normal/x86_64/Pods_RunnerTests_dependency_info.dat
                        LD_DYLIB_INSTALL_NAME = @rpath/Pods_RunnerTests.framework/Pods_RunnerTests
                        LD_GENERATE_MAP_FILE = NO
                        LD_MAP_FILE_PATH =
                        /Users/bdtask/Desktop/mostafiz9900/project_bitbuket/sebaghar_flutter/build/ios/Pods.build/Release-iphonesimulator/Pods-RunnerTests.b
                        uild/Pods_RunnerTests-LinkMap-normal-x86_64.txt
                        LD_NO_PIE = NO
                        LD_QUOTE_LINKER_ARGUMENTS_FOR_COMPILER_DRIVER = YES
                        LD_RUNPATH_SEARCH_PATHS =  /usr/lib/swift @executable_path/Frameworks @loader_path/Frameworks
                        LEGACY_DEVELOPER_DIR = /Applications/Xcode.app/Contents/Frameworks/Xcode3Core.framework/SharedSupport/Developer
                        LEX = lex
                        LIBRARY_DEXT_INSTALL_PATH = /Library/DriverExtensions
                        LIBRARY_FLAG_NOSPACE = YES
                        LIBRARY_FLAG_PREFIX = -l
                        LIBRARY_KEXT_INSTALL_PATH = /Library/Extensions
                        LIBRARY_SEARCH_PATHS =
                        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator/
                        /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator16.4.sdk/usr/lib/swift
                        LINKER_DISPLAYS_MANGLED_NAMES = NO
                        LINK_FILE_LIST_normal_arm64 = 
                        LINK_FILE_LIST_normal_x86_64 = 
                        LINK_WITH_STANDARD_LIBRARIES = YES
                        LLVM_TARGET_TRIPLE_OS_VERSION = ios13.0
                        LLVM_TARGET_TRIPLE_SUFFIX = -simulator
                        LLVM_TARGET_TRIPLE_VENDOR = apple
                        LOCALIZABLE_CONTENT_DIR = 
                        LOCALIZATION_EXPORT_SUPPORTED = YES
                        LOCALIZED_RESOURCES_FOLDER_PATH = Pods_RunnerTests.framework/en.lproj
                        LOCALIZED_STRING_MACRO_NAMES = NSLocalizedString CFCopyLocalizedString
                        LOCALIZED_STRING_SWIFTUI_SUPPORT = YES
                        LOCAL_ADMIN_APPS_DIR = /Applications/Utilities
                        LOCAL_APPS_DIR = /Applications
                        LOCAL_DEVELOPER_DIR = /Library/Developer
                        LOCAL_LIBRARY_DIR = /Library
                        LOCROOT = 
                        LOCSYMROOT = 
                        MACH_O_TYPE = staticlib
                        MAC_OS_X_PRODUCT_BUILD_VERSION = 22A400
                        MAC_OS_X_VERSION_ACTUAL = 130001
                        MAC_OS_X_VERSION_MAJOR = 130000
                        MAC_OS_X_VERSION_MINOR = 130000
                        METAL_LIBRARY_FILE_BASE = default
                        METAL_LIBRARY_OUTPUT_DIR =
                        /Users/bdtask/Desktop/mostafiz9900/project_bitbuket/sebaghar_flutter/build/ios/Release-iphonesimulator/Pods_RunnerTests.framework
                        MODULEMAP_FILE = Target Support Files/Pods-RunnerTests/Pods-RunnerTests.modulemap
                        MODULES_FOLDER_PATH = Pods_RunnerTests.framework/Modules
                        MODULE_CACHE_DIR = /Users/bdtask/Library/Developer/Xcode/DerivedData/ModuleCache.noindex
                        MTL_ENABLE_DEBUG_INFO = NO
                        MTL_FAST_MATH = YES
                        NATIVE_ARCH = arm64e
                        NATIVE_ARCH_32_BIT = i386
                        NATIVE_ARCH_64_BIT = arm64e
                        NATIVE_ARCH_ACTUAL = arm64e
                        NO_COMMON = YES
                        OBJC_ABI_VERSION = 2
                        OBJECT_FILE_DIR =
                        /Users/bdtask/Desktop/mostafiz9900/project_bitbuket/sebaghar_flutter/build/ios/Pods.build/Release-iphonesimulator/Pods-RunnerTests.b
                        uild/Objects
                        OBJECT_FILE_DIR_normal =
                        /Users/bdtask/Desktop/mostafiz9900/project_bitbuket/sebaghar_flutter/build/ios/Pods.build/Release-iphonesimulator/Pods-RunnerTests.b
                        uild/Objects-normal
                        OBJROOT = /Users/bdtask/Desktop/mostafiz9900/project_bitbuket/sebaghar_flutter/build/ios
                        ONLY_ACTIVE_ARCH = NO
                        OS = MACOS
                        OSAC = /usr/bin/osacompile
                        PACKAGE_TYPE = com.apple.package-type.wrapper.framework
                        PASCAL_STRINGS = YES
```

### Flutter Doctor

```shell
bdtask@Bdtasks-iMac ~ % flutter doctor -v 
[✓] Flutter (Channel stable, 3.10.0, on macOS 13.0.1 22A400 darwin-arm64
    (Rosetta), locale en-US)
    • Flutter version 3.10.0 on channel stable at
      /Users/bdtask/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 84a1e904f4 (6 days ago), 2023-05-09 07:41:44 -0700
    • Engine revision d44b5a94c9
    • Dart version 3.0.0
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/bdtask/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Users/bdtask/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9862592
      /Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[✓] Android Studio (version 2022.2)
    • Android Studio at /Users/bdtask/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9862592
      /Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.78.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[✓] Connected device (3 available)            
    • iPhone 14 Pro (mobile) • 01C41DDF-A86F-420C-A1FB-52721BE68A4E • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)        • macos                                •
      darwin-arm64   • macOS 13.0.1 22A400 darwin-arm64 (Rosetta)
    • Chrome (web)           • chrome                               •
      web-javascript • Google Chrome 113.0.5672.92

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

### Checklist before submitting a bug

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment] 2023-05-15 07:59
Duplicate of https://github.com/fluttercommunity/plus_plugins/issues/1672 and https://github.com/fluttercommunity/plus_plugins/issues/1806

Check out this comment: 
https://github.com/fluttercommunity/plus_plugins/issues/1806#issuecomment-1545332556

**Comment by dhruvanbhalara** [comment] 2023-06-20 17:25
@vbuberen As it's already solved can you please close it?

**Closed** 2023-08-04 15:41 UTC
Labels: bug, triage
