### ISSUE TITLE
[Request]: Package Migrating to V2 Embedding for device_info_plus

### ISSUE THREAD

**Issue by Mvhd** [fluttercommunity/plus_plugins#989] opened 2022-07-31 09:52 UTC
### Plugin

device_info_plus

### Use case

Error message while running pub get

This app is using a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to migrate this app to the V2 embedding.
Take a look at the docs for migrating an app: https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects
The plugin `device_info_plus` requires your app to be migrated to the Android embedding v2. Follow the steps on https://flutter.dev/go/android-project-migration and re-run this command.

### Proposal

As outline in the message above. Migrate the package to V2 embedding

**Comment by miquelbeltran** [comment] 2022-07-31 13:16
I thought we migrated already all packages to V2, thanks for reminding us!

**Comment by Goddchen** [comment] 2022-10-01 07:51
Can't reproduce, is this still valid?

**Comment by miquelbeltran** [comment] 2022-10-01 14:53
According to the changelog, this was done in 3.0.0, so marking it as invalid

**Closed by miquelbeltran** 2022-10-01 14:53 UTC
Labels: enhancement, android, device_info_plus, Hacktoberfest

**Comment by jpsarda** [comment] 2023-02-13 10:13
Hello, since I have added device_info_plus to my project, I have this same error when exectuing a pub get :  
`The plugin `device_info_plus` requires your app to be migrated to the Android embedding v2. Follow the steps on https://flutter.dev/go/android-project-migration and re-run this command.`

I've followed the step in the link and my app was already migrated to the Android embedding v2. I'm using device_info_plus v8.1.0
