### ISSUE TITLE
[Bug]: connectivity_plus may crash on Android 12

### ISSUE THREAD

**Issue by canluhuang** [fluttercommunity/plus_plugins#1025] opened 2022-08-16 06:18 UTC
### Platform

Android12

### Plugin

connectivity_plus

### Version

2.3.6+!

### Flutter SDK

3.0.2

### Steps to reproduce

When the connectivity_plus plugin is unregistered, our online version of the app may crash on the Android 12 machine

### Logs

```shell
java.lang.IllegalArgumentException: NetworkCallback was not registered
android.net.ConnectivityManager.unregisterNetworkCallback(ConnectivityManager.java:4605)
dev.fluttercommunity.plus.connectivity.ConnectivityBroadcastReceiver.void onCancel(java.lang.Object)(ConnectivityBroadcastReceiver.java:66)
dev.fluttercommunity.plus.connectivity.ConnectivityPlugin.void teardownChannels()(ConnectivityPlugin.java:51)
dev.fluttercommunity.plus.connectivity.ConnectivityPlugin.void onDetachedFromEngine(io.flutter.embedding.engine.plugins.FlutterPlugin$FlutterPluginBinding)(ConnectivityPlugin.java:29)
io.flutter.embedding.engine.FlutterEngineConnectionRegistry.void remove(java.lang.Class)(FlutterEngineConnectionRegistry.java:273)
io.flutter.embedding.engine.FlutterEngineConnectionRegistry.void remove(java.util.Set)(FlutterEngineConnectionRegistry.java:283)
io.flutter.embedding.engine.FlutterEngineConnectionRegistry.void removeAll()(FlutterEngineConnectionRegistry.java:291)
io.flutter.embedding.engine.FlutterEngineConnectionRegistry.void destroy()(FlutterEngineConnectionRegistry.java:121)
io.flutter.embedding.engine.FlutterEngine.void destroy()(FlutterEngine.java:425)
```

### Flutter Doctor

```shell
Flutter 3.0.2 • channel unknown • unknown source
Framework • revision 2a0a1be03d (8 months ago) • 2021-12-29 22:34:19 +0800
Engine • revision f15f824b57
Tools • Dart 2.17.3 • DevTools 2.12.2
(base) lukehuangdeiMac:.rflutter_sdk lukehuang$ ./rflutter/bin/flutter doctor -v
[✓] Flutter (Channel unknown, 3.0.2-0.100.pre, on macOS 11.6 20G165 darwin-x64, locale zh-Hans-CN)
    • Flutter version 3.0.2-0.100.pre at /Users/lukehuang/.rflutter_sdk/rflutter
    • Upstream repository unknown
    • Framework revision 2a0a1be03d (8 months ago), 2021-12-29 22:34:19 +0800
    • Engine revision f15f824b57
    • Dart version 2.17.3
    • DevTools version 2.12.2

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/lukehuang/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[!] Xcode - develop for iOS and macOS (Xcode 12.5.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ✗ Flutter requires Xcode 13 or higher.
      Download the latest version or update via the Mac App Store.
    ! CocoaPods 1.10.2 out of date (1.11.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin
        usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 211.7798

[✓] IntelliJ IDEA Community Edition (version 2020.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 201.6668.124

[✓] VS Code (version 1.69.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (3 available)
    • IN2010 (mobile) • 61545440 • android-arm64  • Android 11 (API 30)
    • macOS (desktop) • macos    • darwin-x64     • macOS 11.6 20G165 darwin-x64
    • Chrome (web)    • chrome   • web-javascript • Google Chrome 104.0.5112.79

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
```

**Comment by vbuberen** [comment] 2022-10-16 11:12
> When the connectivity_plus plugin is unregistered, our online version of the app may crash on the Android 12 machine

Could you explain what do you mean `unregistered`? There is no listener added and no call to `checkConnectivity()`? 
Would be good to have more info to understand how to reproduce the issue.

**Comment by canluhuang** [comment] 2022-11-08 03:28
This is the error stack：

`
java.lang.IllegalArgumentException: NetworkCallback was not registered
android.net.ConnectivityManager.unregisterNetworkCallback(ConnectivityManager.java:4678)
dev.fluttercommunity.plus.connectivity.ConnectivityBroadcastReceiver.void onCancel(java.lang.Object)(ConnectivityBroadcastReceiver.java:66)
dev.fluttercommunity.plus.connectivity.ConnectivityPlugin.void teardownChannels()(ConnectivityPlugin.java:51)
dev.fluttercommunity.plus.connectivity.ConnectivityPlugin.void onDetachedFromEngine(io.flutter.embedding.engine.plugins.FlutterPlugin$FlutterPluginBinding)(ConnectivityPlugin.java:29)
io.flutter.embedding.engine.FlutterEngineConnectionRegistry.void remove(java.lang.Class)(FlutterEngineConnectionRegistry.java:270)
io.flutter.embedding.engine.FlutterEngineConnectionRegistry.void remove(java.util.Set)(FlutterEngineConnectionRegistry.java:280)
io.flutter.embedding.engine.FlutterEngineConnectionRegistry.void removeAll()(FlutterEngineConnectionRegistry.java:288)
io.flutter.embedding.engine.FlutterEngineConnectionRegistry.void destroy()(FlutterEngineConnectionRegistry.java:121)
io.flutter.embedding.engine.FlutterEngine.void destroy()(FlutterEngine.java:425)
`

<img width="918" alt="image" src="https://user-images.githubusercontent.com/7105187/200468275-6b979dd7-390b-451b-ac50-5dea2b09347c.png">

line 66 may cause the error if NetworkCallback was not unregistered.
I think a try-catch needs to be added here too.

**Comment by vbuberen** [comment] 2022-11-08 07:46
> line 66 may cause the error if NetworkCallback was not unregistered.

Thanks, but this is not what I asked you about as you already provided a stacktrace in the original message and there is definitely no need in a tour of plugin's source code.

What I was asking is to share how you use the plugin to reproduce the behavior you reported. Without it we can't help as I can't reproduce this issue in our `example` app even if comment adding a connectivity listener or calls to `checkConnectivity()`.

Provide either a code snippet on how you use the plugin or a project where it can be reproduced.

**Comment by canluhuang** [comment] 2022-11-11 06:49
hi, @vbuberen 
We did not reproduce this problem during development, but our online monitoring found.
I think you should have received similar feedback, otherwise why did you add try-catch to versions smaller than Android N？

**Comment by vbuberen** [comment] 2022-11-11 07:16
> I think you should have received similar feedback, otherwise why did you add try-catch to versions smaller than Android N？

This is not how bug reports work. If there were similar feedback you would find it in Github issues either open or closed. If you can't provide a reproducer or steps to reproduce it means we can't help you.
As to your `otherwise` - I am not the only person working on this plugin. Moreover, before becoming Plus Plugins developed by a Flutter community these plugins were created and supported by Google. So we might not have all the history of decisions made there.

As there is no reproducer or steps to reproduce I am closing this issue.
There was a number of releases for `connectivity_plus` since your original report, so in case the issue is there in newer builds and you know how to reproduce - you are welcome to open a new one.

**Closed by vbuberen** 2022-11-11 07:16 UTC
Labels: bug, Hacktoberfest, missing info, triage

**Comment by canluhuang** [comment] 2022-11-11 11:13
What I mean is that the version smaller than Android N has added try-catch and also explained in your comment that it is closed without calling listen, and it should be handled in the same way for Android N.
I think this is an obvious problem and don't need to provide reproducing code.

<img width="696" alt="image" src="https://user-images.githubusercontent.com/7105187/201328955-ae6aa2d0-9822-42df-aaf6-23cf673712fa.png">

**Comment by vbuberen** [comment] 2022-11-11 11:34
> I think this is an obvious problem and don't need to provide reproducing code.

If it was so obvious you would have no issues with creating a reproducing case. From my side I explained in one of previous comments that I tried to reproduce a case where app has the plugin, but never adds a listener for connectivity events or calls `check()`.

And since you already started digging into a source code finding `obvious` problems, you are more than welcome to open a PR with fix, but only if you can also provide a confirmation that it fixes some real problem.

Till there is a correct report with a real scenario to reproduce this bug or, even better, some sample project with the problem, we can't help you.
