### ISSUE TITLE
[Question]: Flutter Appbar disappears when using Share

### ISSUE THREAD

**Issue by kylequang** [fluttercommunity/plus_plugins#1988] opened 2023-07-28 03:38 UTC
### What is your question?

Flutter Appbar disappears when using Share
I have the same : [ https://stackoverflow.com/questions/74950793/in-flutter-share-a-link-using-share-plus-then-page-moves-to-status-bar-and-stat](https://stackoverflow.com/questions/74950793/in-flutter-share-a-link-using-share-plus-then-page-moves-to-status-bar-and-stat)

### Checklist before submitting a question

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment] 2023-08-03 19:13
Could you share the code on how your screen looks like?

**Comment by iamrishan** [comment] 2023-08-08 13:47
class FeesPage extends StatelessWidget {
  const FeesPage({super.key});

  Future<void> share() async {
    await Share.share("Example share", subject: "Test subject");
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Plugin example app'),
        ),
        body: Center(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.center,
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              ElevatedButton(
                child: Text('Share text and link'),
                onPressed: share,
              ),
              ElevatedButton(
                child: Text('Share local file'),
                onPressed: share,
              ),
            ],
          ),
        ),
      ),
    );
  }
}

**Comment by iamrishan** [comment] 2023-08-08 13:50
`class FeesPage extends StatelessWidget {
  const FeesPage({super.key});

  Future<void> share() async {
    await Share.share("Example share", subject: "Test subject");
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Plugin example app'),
        ),
        body: Center(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.center,
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              ElevatedButton(
                child: Text('Share text and link'),
                onPressed: share,
              ),
              ElevatedButton(
                child: Text('Share local file'),
                onPressed: share,
              ),
            ],
          ),
        ),
      ),
    );
  }
}
`

**Comment by iamrishan** [comment] 2023-08-08 13:51
```class FeesPage extends StatelessWidget {
  const FeesPage({super.key});

  Future<void> share() async {
    await Share.share("Example share", subject: "Test subject");
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Plugin example app'),
        ),
        body: Center(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.center,
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              ElevatedButton(
                child: Text('Share text and link'),
                onPressed: share,
              ),
              ElevatedButton(
                child: Text('Share local file'),
                onPressed: share,
              ),
            ],
          ),
        ),
      ),
    );
  }
}

**Comment by amerblackbird** [comment] 2023-08-24 07:52
Any solution for this annoying issue ?

**Comment by amerblackbird** [comment] 2023-08-24 07:52
Any solution for this annoying issue ? 

SafeArea doesn't work.

**Comment by fahad-whizpool** [comment] 2023-08-28 05:59
I have been facing same issue on Samsung Galaxy A32 (Android 13). I think Android version is not reason of this issue. Only samesung device. On other device realme C35 (Android-13) it's fine.

**Comment by iamrishan** [comment] 2023-08-29 03:40
my error gone away automatically it is not a bug of Share Plugin it is only on some devices. if you test it out with a production level build you will not see the error and make sure developer mode off when running. you can close the issue now @vbuberen

**Comment by vbuberen** [comment] 2023-08-29 06:02
> my error gone away automatically it is not a bug of Share Plugin it is only on some devices. if you test it out with a production level build you will not see the error and make sure developer mode off when running.

Thanks for your feedback.

In fact, on Android when `Share.share` is used no UI manipulation is done by the plugin as in Android native part standard `Intent` is created for sharing without any changes to window, UI, etc. Thus, there is nothing to fix in the plugin as the issue is caused by the system itself on some devices where people experience this problem.

**Closed by vbuberen** 2023-08-29 06:02 UTC
Labels: question
