### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by jianmin** [fluttercommunity/plus_plugins#1316] opened 2022-11-01 23:32 UTC
### Platform

iOS 16.0

### Plugin

network_info_plus

### Version

3.0.1

### Flutter SDK

3.3.2

### Steps to reproduce

When accessing WiFi information on my iPhone (iOS 16.0), `NetworkInfo.getWifiBSSID()` returned a wrong BSSID. For my test case, the correct BSSID should be `54:af:97:ee:0e:6b`, but got `54:af:97:ee:e:6b`.

For my android devices and iOS devices with 15.x version, it works well. Currently, the problem only happens to my iOS 16.0 iPhone.

### Code Sample

```dart
final info = NetworkInfo();
    String? wifiSSID;
    String? wifiBSSID;
    String? wifiIP;

if (Platform.isAndroid) {
      wifiSSID = await info.getWifiName();
      wifiBSSID = await info.getWifiBSSID();
      wifiIP = await info.getWifiIP();
    } else if (Platform.isIOS) {
      LocationAuthorizationStatus status =
          await info.getLocationServiceAuthorization();
      if (status == LocationAuthorizationStatus.authorizedAlways ||
          status == LocationAuthorizationStatus.authorizedWhenInUse) {
        wifiSSID = await info.getWifiName();
        wifiBSSID = await info.getWifiBSSID();
        wifiIP = await info.getWifiIP();
      } else {
        wifiSSID = await info.getWifiName();
        wifiBSSID = await info.getWifiBSSID();
        wifiIP = await info.getWifiIP();
      }
    } else {
      // not supported
    }
    print("raw bssid: $wifiBSSID");
```

### Logs

```shell
for iOS 16.0:

flutter: raw bssid: 54:af:97:ee:e:6b
flutter: ajaxweaver
flutter: {wifiSSID: ajaxweaver, wifiBSSID: 54:af:97:ee:e:6b, wifiIP: 192.168.68.51}

for Android and iOS 15.x:

I/flutter ( 5130): raw bssid: 54:af:97:ee:0e:6b
I/flutter ( 5130): ajaxweaver
I/flutter ( 5130): {wifiSSID: ajaxweaver, wifiBSSID: 54:af:97:ee:0e:6b, wifiIP: 192.168.68.59}
```

### Flutter Doctor

```shell
[✓] Flutter (Channel stable, 3.3.2, on macOS 12.6 21G115 darwin-arm, locale en-CA)
    • Flutter version 3.3.2 on channel stable at /Users/simonwang/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e3c29ec00c (7 weeks ago), 2022-09-14 08:46:55 -0500
    • Engine revision a4ff2c53d8
    • Dart version 2.18.1
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/simonwang/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A309
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.52.0

[✓] Connected device (4 available)
    • Pixel 6 (mobile)        • 21121FDF6006BK            • android-arm64  • Android 12 (API 32)
    • Simon’s iPhone (mobile) • 00008110-00044C2E2138801E • ios            • iOS 16.0 20A362
    • macOS (desktop)         • macos                     • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)            • chrome                    • web-javascript • Google Chrome 107.0.5304.87
    ! Error: Simon’s Apple Watch needs to connect to determine its availability. Check the connection between the device and its companion iPhone, and the connection between the iPhone and Xcode. Both devices may also need to be restarted and
      unlocked. (code 1)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

### Checklist before submitting a bug

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by miquelbeltran** [comment] 2022-11-02 06:04
My understanding is that the plugin simply returns what the OS returns using this API: https://developer.apple.com/documentation/networkextension/nehotspotnetwork/1618936-bssid

See https://github.com/fluttercommunity/plus_plugins/blob/main/packages/network_info_plus/network_info_plus/ios/Classes/FLTHotspotNetworkInfoProvider.m

I guess you will have to report that to Apple :)

**Comment by vbuberen** [comment] 2022-11-27 23:09
Closing as it is explained that the issue is not in the plugin.

**Closed by vbuberen** 2022-11-27 23:09 UTC
Labels: bug
