### ISSUE TITLE
identifierForVendor change when remove and then reinstall app

### ISSUE THREAD

**Issue by quachanhdung** [fluttercommunity/plus_plugins#452] opened 2021-09-11 04:59 UTC
## System info

Issue occurs on: iOS / Android / both
Plugin name:
Plugin version:
Flutter doctor output:

```
paste it here...
```

## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

```
```

**Comment by mhadaily** [comment] 2021-09-28 04:36
@quachanhdung can you elaborate more? and add step to reproduce?

**Comment by Leffe108** [comment] 2022-03-26 13:22
Looks like a duplicate of https://github.com/fluttercommunity/plus_plugins/issues/447

[Apple docs](https://developer.apple.com/documentation/uikit/uidevice/1620059-identifierforvendor) says that this is expected behaviour. (unless you publish more than one app, then it resets when users has removed all your published apps)

**Comment by mhadaily** [comment] 2022-03-29 08:56
a duplicate of https://github.com/fluttercommunity/plus_plugins/issues/447

**Closed by mhadaily** 2022-03-29 08:56 UTC
Labels: bug
