### ISSUE TITLE
[package_info_plus] Wrong version on windows

### ISSUE THREAD

**Issue by gutisalex** [fluttercommunity/plus_plugins#343] opened 2021-07-05 08:36 UTC
Hey,

Steps to reproduce:
I've set the version to 1.0.22+22 in pubspec yaml...

I use a function to get the version:

```dart 
Future<String> getAppVersion() async {
    PackageInfo packageInfo = await PackageInfo.fromPlatform();
    return packageInfo.version;
  }
```

Result:
On Android I am getting 1.0.2
On Windows I am getting 1.0.0

Expected:
On Windows it should also be 1.0.2

**Comment by mhadaily** [comment] 2021-07-06 17:07
@jpnurmi do you have any idea for this?

**Comment by jpnurmi** [comment] 2021-07-06 17:20
I recall it's the version of the .exe, which should be possible to define with CMake.

**Comment by stuartmorgan** [comment] 2021-07-10 21:20
> I've set the version to 1.0.22+22 in pubspec yaml

This doesn't currently do anything for Windows builds; see https://github.com/flutter/flutter/issues/73652

**Comment by sgsm74** [comment] 2021-12-06 11:06
same issue, any solution?

**Comment by Eerey** [comment] 2022-04-12 12:49
Same here for windows

**Comment by stuartmorgan** [comment] 2022-04-12 14:09
Everyone will have this behavior on Windows because, per my comment above, that's how Flutter currently works. The version in `pubspec.yaml` has no impact on the Windows executable you get from `flutter build`, you have to change the version in `Runner.rc`.

**Comment by chitgoks** [comment] 2022-04-23 02:05
Is this the same reason for the version now? 1.4.2. Instead of the value 1.0.2 i get 1 only. no decimal. (in windows)

**Comment by ismanong** [comment] 2022-07-26 09:44
The newest ones are already supported and can get the version number correctly

**Comment by lgLindstrom** [comment] 2022-10-13 13:15
I have a old windows project where this problem occur. Duplication the example project in package_info_plus works okay, but not my old project. This leads me to believe that I must update something in my project.
What ???

**Comment by he0119** [comment] 2022-10-13 13:21
> I have a old windows project where this problem occur. Duplication the example project in package_info_plus works okay, but not my old project. This leads me to believe that I must update something in my project. What ???

https://docs.flutter.dev/development/platform-integration/windows/version-migration

>Flutter 3.3 added support for setting the Windows app’s version from the pubspec.yaml file or through the --build-name and --build-number build arguments. For more information, refer to the [Build and release a Windows app](https://docs.flutter.dev/deployment/windows#updating-the-apps-version-number) documentation.

Projects created before Flutter version 3.3 need to be migrated to support versioning.

**Comment by neoDD69** [comment] 2022-12-22 17:44
IMHO, and after few test, the problem IS NOT an issue of thi package [package_info_plus] , but the COMPILER used by Flutter.

If you see the details of the .exe with "Windows Explorer", you will see the same number that the [package_info_plus] return.
![image](https://user-images.githubusercontent.com/2903187/209194699-bdb22678-8c93-48dc-964d-64ad510044d9.png)
![image](https://user-images.githubusercontent.com/2903187/209194825-7f0b4581-b83d-494e-8660-0503b5fcf7a6.png)

If you search you will found a lot of thread about the version of Flutter-Windows app and all talk about a runnner.rc

**Comment by Levi-Lesches** [comment] 2023-03-14 03:09
This is fixed now that https://github.com/flutter/flutter/issues/73652

**Comment by bksubhuti** [comment] 2023-05-21 05:18
I was about to leave an issue.. but I also had the same problem.  If you had started a project before Flutter 3.3, then your Windows build will be "stale" and not work with this package "as expected"  Getting the version and build from the yaml.  You will be saying "It works in Android, but not in Windows."
**It would be good to document this issue in the package info readme to tell people to upgrade the windows build**.. 

**To solve this problem** 
Delete the windows directory of your project and do the flutter create again.
`flutter create --platforms=windows .`

You can see this link here
https://docs.flutter.dev/platform-integration/windows/version-migration

After doing this, you will then be able to get the desired results.

In any case.. I appreciate this package very much and we ship to 5 Os's.  We have a project that was started a while back and had trouble with determining version numbers because we hardcoded it.. and we are lazy to change every time.  However, the build number increments are required for app store submission, so we cannot be lazy with that.

It might just be that older projects that started the flutter create with windows only one year ago will be looking for this package_info addon as a solution, yet encounter these same errors.
I also suggest a way to place issues a little easier.  I did a few things and then realized I would have to compile the example program first.. so I lost my writing and gave up.  Compiling the given example program would probably still give me an error, because I often have a project used for compiling sample programs.  And if my stub was old enough, that would be an older windows setup.

**Comment by vbuberen** [comment] 2023-08-05 10:23
@bksubhuti Thank you very much for such detailed feedback. I will update the documentation to explicitly mention requirement to migrate.

**Closed** 2023-08-12 22:21 UTC
Labels: bug, package_info_plus, Hacktoberfest
