### ISSUE TITLE
[Bug]: info.getWifiName() return null

### ISSUE THREAD

**Issue by minhdangoz** [fluttercommunity/plus_plugins#1258] opened 2022-10-18 03:14 UTC
### Platform

Android 12

### Plugin

network_info_plus

### Version

2.3.2

### Flutter SDK

3.3.4

### Steps to reproduce

![image](https://user-images.githubusercontent.com/3844258/196326182-2046110c-d098-450b-ad54-254ca696eb94.png)
Currently using latest version of network info plus but can not get SSID name

### Code Sample

```dart
Future<void> _initNetworkInfo() async {
    String? wifiName,
        wifiBSSID,
        wifiIPv4,
        wifiIPv6,
        wifiGatewayIP,
        wifiBroadcast,
        wifiSubmask;

    try {
      if (!kIsWeb && Platform.isIOS) {
        var status = await _networkInfo.getLocationServiceAuthorization();
        if (status == LocationAuthorizationStatus.notDetermined) {
          status = await _networkInfo.requestLocationServiceAuthorization();
        }
        if (status == LocationAuthorizationStatus.authorizedAlways ||
            status == LocationAuthorizationStatus.authorizedWhenInUse) {
          wifiName = await _networkInfo.getWifiName();
        } else {
          wifiName = await _networkInfo.getWifiName();
        }
      } else {
        wifiName = await _networkInfo.getWifiName();
      }
    } on PlatformException catch (e) {
      developer.log('Failed to get Wifi Name', error: e);
      wifiName = 'Failed to get Wifi Name';
    }

    try {
      if (!kIsWeb && Platform.isIOS) {
        var status = await _networkInfo.getLocationServiceAuthorization();
        if (status == LocationAuthorizationStatus.notDetermined) {
          status = await _networkInfo.requestLocationServiceAuthorization();
        }
        if (status == LocationAuthorizationStatus.authorizedAlways ||
            status == LocationAuthorizationStatus.authorizedWhenInUse) {
          wifiBSSID = await _networkInfo.getWifiBSSID();
        } else {
          wifiBSSID = await _networkInfo.getWifiBSSID();
        }
      } else {
        wifiBSSID = await _networkInfo.getWifiBSSID();
      }
    } on PlatformException catch (e) {
      developer.log('Failed to get Wifi BSSID', error: e);
      wifiBSSID = 'Failed to get Wifi BSSID';
    }

    try {
      wifiIPv4 = await _networkInfo.getWifiIP();
    } on PlatformException catch (e) {
      developer.log('Failed to get Wifi IPv4', error: e);
      wifiIPv4 = 'Failed to get Wifi IPv4';
    }

    try {
      if (!Platform.isWindows) {
        wifiIPv6 = await _networkInfo.getWifiIPv6();
      }
    } on PlatformException catch (e) {
      developer.log('Failed to get Wifi IPv6', error: e);
      wifiIPv6 = 'Failed to get Wifi IPv6';
    }

    try {
      if (!Platform.isWindows) {
        wifiSubmask = await _networkInfo.getWifiSubmask();
      }
    } on PlatformException catch (e) {
      developer.log('Failed to get Wifi submask address', error: e);
      wifiSubmask = 'Failed to get Wifi submask address';
    }

    try {
      if (!Platform.isWindows) {
        wifiBroadcast = await _networkInfo.getWifiBroadcast();
      }
    } on PlatformException catch (e) {
      developer.log('Failed to get Wifi broadcast', error: e);
      wifiBroadcast = 'Failed to get Wifi broadcast';
    }

    try {
      if (!Platform.isWindows) {
        wifiGatewayIP = await _networkInfo.getWifiGatewayIP();
      }
    } on PlatformException catch (e) {
      developer.log('Failed to get Wifi gateway address', error: e);
      wifiGatewayIP = 'Failed to get Wifi gateway address';
    }

    setState(() {
      _connectionStatus = 'Wifi Name: $wifiName\n'
          'Wifi BSSID: $wifiBSSID\n'
          'Wifi IPv4: $wifiIPv4\n'
          'Wifi IPv6: $wifiIPv6\n'
          'Wifi Broadcast: $wifiBroadcast\n'
          'Wifi Gateway: $wifiGatewayIP\n'
          'Wifi Submask: $wifiSubmask\n';
    });
  }
```

### Logs

```shell
[   +3 ms] Stopping app 'app.apk' on SM A715F.
[        ] executing: /Users/jimmy/Library/Android/sdk/platform-tools/adb -s R58N12KYW1V shell am force-stop dev.fluttercommunity.plus.network_info_plus_example
[ +215 ms] executing: /Users/jimmy/Library/Android/sdk/platform-tools/adb -s R58N12KYW1V shell pm list packages dev.fluttercommunity.plus.network_info_plus_example
[ +127 ms] package:dev.fluttercommunity.plus.network_info_plus_example
[   +1 ms] executing: /Users/jimmy/Library/Android/sdk/platform-tools/adb -s R58N12KYW1V shell cat /data/local/tmp/sky.dev.fluttercommunity.plus.network_info_plus_example.sha1
[  +55 ms] 2c0a934b1bad6594d292e190ba705226d29535e5
[   +1 ms] Latest build already installed.
[        ] executing: /Users/jimmy/Library/Android/sdk/platform-tools/adb -s R58N12KYW1V shell -x logcat -v time -t 1
[ +551 ms] --------- beginning of system
           10-18 10:09:27.298 V/MdnieScenarioControlService( 1302): mAclOffEnabled : false mAclPreviewState : false mAclCompensationState : false
[  +12 ms] executing: /Users/jimmy/Library/Android/sdk/platform-tools/adb -s R58N12KYW1V shell am start -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x20000000 --ez enable-dart-profiling true --ez enable-checked-mode true --ez verify-entry-points true dev.fluttercommunity.plus.network_info_plus_example/io.flutter.embedding.android.FlutterActivity
[ +150 ms] Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x20000000 cmp=dev.fluttercommunity.plus.network_info_plus_example/io.flutter.embedding.android.FlutterActivity (has extras) }
[        ] Waiting for observatory port to be available...
[ +623 ms] Observatory URL on device: http://127.0.0.1:41569/6nSEPYQxzMg=/
[        ] executing: /Users/jimmy/Library/Android/sdk/platform-tools/adb -s R58N12KYW1V forward tcp:0 tcp:41569
[  +25 ms] 64243
[        ] Forwarded host port 64243 to device port 41569 for Observatory
[   +5 ms] Caching compiled dill
[  +54 ms] Connecting to service protocol: http://127.0.0.1:64243/6nSEPYQxzMg=/
[ +215 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at http://127.0.0.1:64243/6nSEPYQxzMg=/.
[ +164 ms] DDS is listening at http://127.0.0.1:64246/GlG2NF4cbis=/.
[  +72 ms] Successfully connected to service protocol: http://127.0.0.1:64243/6nSEPYQxzMg=/
[  +73 ms] DevFS: Creating new filesystem on the device (null)
[  +23 ms] DevFS: Created new filesystem on the device (file:///data/user/0/dev.fluttercommunity.plus.network_info_plus_example/code_cache/exampleIINOKH/example/)
[   +2 ms] Updating assets
[ +116 ms] Syncing files to device SM A715F...
[   +1 ms] Compiling dart to kernel with 0 updated files
[        ] Processing bundle.
[        ] <- recompile package:network_info_plus_example/main.dart 7be1d04c-ffd0-4338-b40b-509f9367c724
[        ] <- 7be1d04c-ffd0-4338-b40b-509f9367c724
[   +2 ms] Bundle processing done.
[ +125 ms] Updating files.
[        ] DevFS: Sync finished
[   +1 ms] Syncing files to device SM A715F... (completed in 130ms)
[        ] Synced 0.0MB.
[   +1 ms] <- accept
[   +3 ms] Connected to _flutterView/0xb400007d6ac20820.
[   +3 ms] Flutter run key commands.
[   +1 ms] r Hot reload. 🔥🔥🔥
[        ] R Hot restart.
[        ] h List all available interactive commands.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] 💪 Running with sound null safety 💪
[        ] An Observatory debugger and profiler on SM A715F is available at: http://127.0.0.1:64246/GlG2NF4cbis=/
[ +307 ms] The Flutter DevTools debugger and profiler on SM A715F is available at: http://127.0.0.1:9100?uri=http://127.0.0.1:64246/GlG2NF4cbis=/
[  +12 ms] I/BufferQueueProducer(11348): [SurfaceView - dev.fluttercommunity.plus.network_info_plus_example/io.flutter.embedding.android.FlutterActivity@b2b70ab@0#1(BLAST Consumer)1](id:2c5400000001,api:1,p:11348,c:11348) queueBuffer: queued for the first time.
[  +17 ms] I/SurfaceView@b2b70ab(11348): uSP: rtp = Rect(0, 0 - 1080, 2361) rtsw = 1080 rtsh = 2361
[        ] I/SurfaceView@b2b70ab(11348): onSSPAndSRT: pl = 0 pt = 0 sx = 1.0 sy = 1.0
[   +3 ms] I/SurfaceView@b2b70ab(11348): aOrMT: uB = true t = android.view.SurfaceControl$Transaction@27296b2 fN = 1 android.view.SurfaceView.access$500:124 android.view.SurfaceView$SurfaceViewPositionUpdateListener.positionChanged:1728 android.graphics.RenderNode$CompositePositionUpdateListener.positionChanged:319 
[        ] I/SurfaceView@b2b70ab(11348): aOrMT: vR.mWNT, vR = ViewRootImpl@cb8469e[FlutterActivity]
[        ] I/ViewRootImpl@cb8469e[FlutterActivity](11348): mWNT: t = android.view.SurfaceControl$Transaction@27296b2 fN = 1 android.view.SurfaceView.applyOrMergeTransaction:1628 android.view.SurfaceView.access$500:124 android.view.SurfaceView$SurfaceViewPositionUpdateListener.positionChanged:1728 
[        ] I/ViewRootImpl@cb8469e[FlutterActivity](11348): mWNT: merge t to BBQ
[  +10 ms] I/BufferQueueProducer(11348): [ViewRootImpl@cb8469e[FlutterActivity]#0(BLAST Consumer)0](id:2c5400000000,api:1,p:11348,c:11348) queueBuffer: queued for the first time.
[   +2 ms] I/ViewRootImpl@cb8469e[FlutterActivity](11348): [DP] pdf(0) 1 android.view.ViewRootImpl.lambda$addFrameCompleteCallbackIfNeeded$3$ViewRootImpl:4969 android.view.ViewRootImpl$$ExternalSyntheticLambda16.run:6 android.os.Handler.handleCallback:938 
[        ] I/ViewRootImpl@cb8469e[FlutterActivity](11348): [DP] rdf()
[        ] D/ViewRootImpl@cb8469e[FlutterActivity](11348): reportDrawFinished (fn: -1) 
[  +37 ms] I/ViewRootImpl@cb8469e[FlutterActivity](11348): MSG_WINDOW_FOCUS_CHANGED 1 1
[        ] D/InputMethodManager(11348): startInputInner - Id : 0
[        ] I/InputMethodManager(11348): startInputInner - mService.startInputOrWindowGainedFocus
[  +10 ms] D/InputMethodManager(11348): startInputInner - Id : 0
[+3248 ms] Application finished.
```

### Flutter Doctor

```shell
flutter doctor -v
[✓] Flutter (Channel stable, 3.3.4, on macOS 12.6 21G115 darwin-x64, locale en-US)
    • Flutter version 3.3.4 on channel stable at /Users/jimmy/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eb6d86ee27 (13 days ago), 2022-10-04 22:31:45 -0700
    • Engine revision c08d7d5efc
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/jimmy/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.72.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (5 available)
    • SM A715F (mobile)          • R58N12KYW1V                          • android-arm64  • Android 12 (API 31)
    • iPhone 12 Pro Max (mobile) • DBCAE572-F1DA-4768-8194-BAB753E509AA • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • iPhone 13 mini (mobile)    • F8DFFAB6-805B-44E0-B6FF-6517C1776729 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • macOS 12.6 21G115
      darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome
      106.0.5249.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

### Checklist before submitting a bug

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by minhdangoz** [comment] 2022-10-18 04:16
Update:

add these permissions to the library android manifest file then it works (not application manifest)


<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>

**Comment by ngominhtrungit** [comment] 2022-10-22 15:42
@vbuberen I using flutter version 3.0.5, when pub get network_info_plus: ^3.0.1 
return error:
`Running "flutter pub get" in check_mac_andress...               
Because every version of flutter_test from sdk depends on meta 1.7.0 and network_info_plus >=2.2.0 depends on meta ^1.8.0, flutter_test from sdk is incompatible with network_info_plus >=2.2.0.
So, because check_mac_andress depends on both network_info_plus ^3.0.1 and flutter_test from sdk, version solving failed.
pub get failed (1; So, because check_mac_andress depends on both network_info_plus ^3.0.1 and flutter_test from sdk, version solving failed.)
Process finished with exit code 1`

pls help me

**Comment by vbuberen** [comment] 2022-10-22 20:37
> @vbuberen I using flutter version 3.0.5, when pub get network_info_plus: ^3.0.1 return error: `Running "flutter pub get" in check_mac_andress... Because every version of flutter_test from sdk depends on meta 1.7.0 and network_info_plus >=2.2.0 depends on meta ^1.8.0, flutter_test from sdk is incompatible with network_info_plus >=2.2.0. So, because check_mac_andress depends on both network_info_plus ^3.0.1 and flutter_test from sdk, version solving failed. pub get failed (1; So, because check_mac_andress depends on both network_info_plus ^3.0.1 and flutter_test from sdk, version solving failed.) Process finished with exit code 1`
> 

It is not related to this issue. Update your Flutter version to the latest.

**Comment by pdt590** [comment] 2022-10-23 02:37
> This issue is fixed in version `3.0.0`. Please check and let us know.

Tested on network_info_plus^3.0.1, the issue has not fixed yet. Thanks

**Comment by vbuberen** [comment] 2022-10-23 09:00
> Tested on network_info_plus^3.0.1, the issue has not fixed yet. Thanks

I would need info from on how to reproduce as both 3.0.0 and 3.0.1 return proper SSID and BSSID for me on Android 12 and 13 in our example app. Note, you need to provide location permission as well to get these 2 fields.

**Comment by vbuberen** [comment] 2022-10-27 09:04
@minhdangoz Have you checked how it works for you in 3.0.0?

@pdt590 Would you provide a reproducer?

**Comment by pdt590** [comment] 2022-10-27 15:03
> @minhdangoz Have you checked how it works for you in 3.0.0?
> 
> @pdt590 Could you provide a reproducer?

I will try

**Comment by JulianMod** [comment] 2022-11-09 15:12
Hello, I'm encountering the same problem. Is there any time expectancy for the solution?

**Comment by miquelbeltran** [comment] 2022-11-09 17:04
> Is there any time expectancy for the solution?

The plus_plugins is an open source project maintained by volunteers, so solving issues depends on their time, knowledge, and motivation to do so. Asking for updates/ETA doesn't help anyone. Instead, you can help by providing more information about the issue, researching possible solutions, and even submitting a PR with a fix.

**Comment by JulianMod** [comment] 2022-11-09 17:49
It was not my intention to bother anyone. I already did research of possible solutions before posting my problem here. This thread seemed to be one month old so my thought was only to refresh it

**Comment by miquelbeltran** [comment] 2022-11-09 18:06
I just realized that in your report, you were not using the latest version of network_info_plus, and yet you checked the option `"I'm using the latest version of the plugin"` which is not true because 3.0.1 was released 20 days ago, and you are using 2.1.4.

**Comment by JulianMod** [comment] 2022-11-09 18:11
Thank you, that solved my issue

**Comment by pdt590** [comment] 2022-11-10 03:24
- Device: Redmi Note 10S
- Android version: 12
- Test version: network_info_plus^3.0.1
- Flutter SDK: 3.3.7
- Permission (android\app\src\main\AndroidManifest.xml)
```
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
    <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.CHANGE_WIFI_STATE" />
```
- Log
```
√  Built build\app\outputs\flutter-apk\app-debug.apk.
D/FlutterLocationService(13752): Creating service.
D/FlutterLocationService(13752): Binding to location service.
I/s_smarthome_ap(13752): Compiler allocated 4460KB to compile void android.view.ViewRootImpl.performTraversals()
Connecting to VM Service at ws://127.0.0.1:56021/F4YkdFrOk3Y=/ws
W/Choreographer(13752): Frame time is 0.179207  now = 305350584941  timestampNanos = 305350764148 ms in the future!  Check that graphics HAL is generating vsync timestamps using the correct timebase.
E/ion     (13752): ioctl c0044901 failed with code -1: Invalid argument
D/hw-ProcessState(13752): Binder ioctl to enable oneway spam detection failed: Invalid argument
E/OpenGLRenderer(13752): fbcNotifyFrameComplete error: undefined symbol: fbcNotifyFrameComplete
E/OpenGLRenderer(13752): fbcNotifyNoRender error: undefined symbol: fbcNotifyNoRender
D/DecorView[](13752): onWindowFocusChanged hasWindowFocus true
```
- Results
Wifi Name: null
[img1](https://1drv.ms/u/s!AhIUQEP6aaoPitYaz2VvhUJj9VgLSQ?e=5zvex9)
[img2](https://1drv.ms/u/s!AhIUQEP6aaoPitYXnNfo6-IzPYO-4A?e=DPHVEv)

**Comment by JulianMod** [comment] 2022-11-10 10:37
Can you go to app info and check if the location permissions are allowed?

**Comment by vbuberen** [comment] 2022-11-10 10:53
@pdt590 This is not a reproducer. Reproducer - project which I can run and test your claim.

From the info you provided there is nothing to show that you actually provided required permissions in the app. It is not enough to declare them in AndroidManifest. You need to request them at runtime or phone settings via Settings -> Apps -> Your App -> Permissions

**Comment by pdt590** [comment] 2022-11-10 11:05
> @pdt590 This is not a reproducer. Reproducer - project which I can run and test your claim.
> 
> From the info you provided there is nothing to show that you actually provided required permissions in the app. It is not enough to declare them in AndroidManifest. You need to request them at runtime or phone settings via Settings -> Apps -> Your App -> Permissions

@vbuberen @JulianMod 
My fault, i enabled Location permission and it worked.
Thank you for your support

**Comment by JulianMod** [comment] 2022-11-10 11:22
Happy to help :)

**Comment by miquelbeltran** [comment] 2022-11-10 12:38
Since this is confirmed to work and is correctly documented on the package README, I am closing this issue. Create a new ticket if the issue rises again.

**Closed by miquelbeltran** 2022-11-10 12:38 UTC
Labels: bug, triage
