### ISSUE TITLE
[Bug]: 使用或覆盖了已过时的 API

### ISSUE THREAD

**Issue by LinHaoLove** [fluttercommunity/plus_plugins#1041] opened 2022-08-29 01:14 UTC
### Platform

any

### Plugin

network_info_plus

### Version

2.1.4+1

### Flutter SDK

macos arm64 3.0.5 stable

### Steps to reproduce

1，first build.
2，first run in release mode.

### Code Sample

```dart
xxxxx/.pub-cache/hosted/pub.flutter-io.cn/network_info_plus-2.1.4+1/android/src/main/java/dev/fluttercommunity/plus/network_info/NetworkInfo.java使用或覆盖了已过时的 API。
xxxxx/.pub-cache/hosted/pub.flutter-io.cn/camera_android-0.10.0+1/android/src/main/java/io/flutter/plugins/camera/features/resolution/ResolutionFeature.java:154: 警告: [deprecation] CamcorderProfile中的get(int,int)已过时
          return CamcorderProfile.get(cameraId, CamcorderProfile.QUALITY_HIGH);
xxxxx/.pub-cache/hosted/pub.flutter-io.cn/camera_android-0.10.0+1/android/src/main/java/io/flutter/plugins/camera/features/resolution/ResolutionFeature.java:158: 警告: [deprecation] CamcorderProfile中的get(int,int)已过时
          return CamcorderProfile.get(cameraId, CamcorderProfile.QUALITY_2160P);
xxxxx/.pub-cache/hosted/pub.flutter-io.cn/camera_android-0.10.0+1/android/src/main/java/io/flutter/plugins/camera/features/resolution/ResolutionFeature.java:162: 警告: [deprecation] CamcorderProfile中的get(int,int)已过时
          return CamcorderProfile.get(cameraId, CamcorderProfile.QUALITY_1080P);
                                 ^
xxxxx/.pub-cache/hosted/pub.flutter-io.cn/camera_android-0.10.0+1/android/src/main/java/io/flutter/plugins/camera/features/resolution/ResolutionFeature.java:166: 警告: [deprecation] CamcorderProfile中的get(int,int)已过时
          return CamcorderProfile.get(cameraId, CamcorderProfile.QUALITY_720P);
                                 ^
xxxxx/.pub-cache/hosted/pub.flutter-io.cn/camera_android-0.10.0+1/android/src/main/java/io/flutter/plugins/camera/features/resolution/ResolutionFeature.java:170: 警告: [deprecation] CamcorderProfile中的get(int,int)已过时
          return CamcorderProfile.get(cameraId, CamcorderProfile.QUALITY_480P);
                                 ^
xxxxx/.pub-cache/hosted/pub.flutter-io.cn/camera_android-0.10.0+1/android/src/main/java/io/flutter/plugins/camera/features/resolution/ResolutionFeature.java:174: 警告: [deprecation] CamcorderProfile中的get(int,int)已过时
          return CamcorderProfile.get(cameraId, CamcorderProfile.QUALITY_QVGA);
                                 ^
xxxxx/.pub-cache/hosted/pub.flutter-io.cn/camera_android-0.10.0+1/android/src/main/java/io/flutter/plugins/camera/features/resolution/ResolutionFeature.java:178: 警告: [deprecation] CamcorderProfile中的get(int,int)已过时
          return CamcorderProfile.get(cameraId, CamcorderProfile.QUALITY_LOW);
```

### Logs

```shell
[  +29 ms] xxxxx/.pub-cache/hosted/pub.flutter-io.cn/camera_android-0.10.0+1/android/src/main/java/io/flutter/plugins/camera/features/resolution/ResolutionFeature.java:154: 警告: [deprecation]
CamcorderProfile中的get(int,int)已过时
[   +9 ms]           return CamcorderProfile.get(cameraId, CamcorderProfile.QUALITY_HIGH);
[        ]                                  ^
[        ] xxxxx/.pub-cache/hosted/pub.flutter-io.cn/camera_android-0.10.0+1/android/src/main/java/io/flutter/plugins/camera/features/resolution/ResolutionFeature.java:158: 警告: [deprecation]
CamcorderProfile中的get(int,int)已过时
[        ]           return CamcorderProfile.get(cameraId, CamcorderProfile.QUALITY_2160P);
[        ]                                  ^
[        ] xxxxx/.pub-cache/hosted/pub.flutter-io.cn/camera_android-0.10.0+1/android/src/main/java/io/flutter/plugins/camera/features/resolution/ResolutionFeature.java:162: 警告: [deprecation]
CamcorderProfile中的get(int,int)已过时
[   +2 ms]           return CamcorderProfile.get(cameraId, CamcorderProfile.QUALITY_1080P);
[        ]                                  ^
[        ] xxxxx/.pub-cache/hosted/pub.flutter-io.cn/camera_android-0.10.0+1/android/src/main/java/io/flutter/plugins/camera/features/resolution/ResolutionFeature.java:166: 警告: [deprecation]
CamcorderProfile中的get(int,int)已过时
[        ]           return CamcorderProfile.get(cameraId, CamcorderProfile.QUALITY_720P);
[        ]                                  ^
[        ] xxxxx/.pub-cache/hosted/pub.flutter-io.cn/camera_android-0.10.0+1/android/src/main/java/io/flutter/plugins/camera/features/resolution/ResolutionFeature.java:170: 警告: [deprecation]
CamcorderProfile中的get(int,int)已过时
[  +22 ms]           return CamcorderProfile.get(cameraId, CamcorderProfile.QUALITY_480P);
[        ]                                  ^
[        ] xxxxx/.pub-cache/hosted/pub.flutter-io.cn/camera_android-0.10.0+1/android/src/main/java/io/flutter/plugins/camera/features/resolution/ResolutionFeature.java:174: 警告: [deprecation]
CamcorderProfile中的get(int,int)已过时
[        ]           return CamcorderProfile.get(cameraId, CamcorderProfile.QUALITY_QVGA);
[        ]                                  ^
[        ] xxxxx/.pub-cache/hosted/pub.flutter-io.cn/camera_android-0.10.0+1/android/src/main/java/io/flutter/plugins/camera/features/resolution/ResolutionFeature.java:178: 警告: [deprecation]
CamcorderProfile中的get(int,int)已过时
[        ]           return CamcorderProfile.get(cameraId, CamcorderProfile.QUALITY_LOW);
[        ]                                  ^
[        ] 7 个警告
```

### Flutter Doctor

```shell
• No issues found!
```

**Comment by vbuberen** [comment] 2022-09-28 07:43
Network_info_plus on Android indeed uses deprecated API for old devices, but it is not a bug or issue, thus, closing it.

**Closed by vbuberen** 2022-09-28 07:43 UTC
Labels: network_info_plus
