### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by MuthuHere** [fluttercommunity/plus_plugins#2161] opened 2023-09-26 23:56 UTC
### Platform

Android 8+

### Plugin

device_info_plus

### Version

9.0.3

### Flutter SDK

 3.10.4

### Steps to reproduce

After integrating with this mentioned library i am getting this following error,

Could not find method namespace() for arguments [dev.fluttercommunity.plus.device_info] on extension 'android' of type com.android.build.gradle.LibraryExtension.

### Logs

```shell
[   +1 ms] FAILURE: Build failed with an exception.
[   +2 ms] * Where:
[        ] Build file '/Users/muthu/.pub-cache/hosted/pub.dev/device_info_plus-9.0.3/android/build.gradle' line: 30
[        ] * What went wrong:
[        ] A problem occurred evaluating project ':device_info_plus'.
[        ] > Could not find method namespace() for arguments [dev.fluttercommunity.plus.device_info] on extension
'android' of type com.android.build.gradle.LibraryExtension.
[        ] * Try:
[        ] > Run with --debug option to get more log output.
[        ] > Run with --scan to get full insights.
[        ] * Exception is:
[        ] org.gradle.api.GradleScriptException: A problem occurred evaluating project ':device_info_plus'.
[        ]      at
org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:
93)
[        ]      at
org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.lambda$apply$0(DefaultScriptPluginFactory.java
:133)
[        ]      at org.gradle.configuration.ProjectScriptTarget.addConfiguration(ProjectScriptTarget.java:79)
[        ]      at
org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:136)
[        ]      at org.gradle.configuration.BuildOperationScriptPlugin$1.run(BuildOperationScriptPlugin.java:65)
[        ]      at
org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
[        ]      at
org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
[        ]      at
org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
[        ]      at
org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
[        ]      at
org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
[ +272 ms]      at
```

### Flutter Doctor

```shell
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.4, on macOS 13.1 22C65 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.82.2)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

### Checklist before submitting a bug

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment] 2023-09-29 12:28
Update Android Gradle Plugin in your project as required since version 9.0.0: https://pub.dev/packages/device_info_plus/changelog#900

Duplicate of #2020 and many other similar bugs we had here.

P.S. Don't check the checkmark for first 2 items in the checklist as it seems that you definitely didn't bother yourself searching the issue in Google or StackOverflow before opening an issue here.

**Closed by vbuberen** 2023-09-29 12:28 UTC
