### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by HamzaMihfad** [fluttercommunity/plus_plugins#2226] opened 2023-10-06 09:34 UTC
### Platform

iOS 16.7

### Plugin

connectivity_plus

### Version

4.0.2

### Flutter SDK

3.13.6

### Steps to reproduce
Just wasted 4 days becuase of this package. it's working on debug mode with no issues, but craches the app in release mode.
The package was working fine, but after I updated xCode to the latest version that supports iOS 17, the app started crashing immediatly after launching it on iOS versions before iOS 17, but it is working on iOS 17.

### Logs

```shell
No logs, because it is working on debug mode, but not working in release mode.
```

### Flutter Doctor

```shell
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.6, on macOS 14.0 23A344 darwin-arm64, locale en-MA)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.82.3)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!
```

### Checklist before submitting a bug

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by raqeta** [comment] 2023-10-06 19:45
Same thing, simulator - ok 16.4 simulator - ок, 17 device - ok, 16.3.1 - crash here VVV
<img width="684" alt="Снимок экрана 2023-10-06 в 22 44 27" src="https://github.com/fluttercommunity/plus_plugins/assets/741051/bca72262-b58d-46c4-a0d8-3a8cb1a73c61">

**Comment by HamzaMihfad** [comment] 2023-10-06 20:25
@raqeta  I solved this issue but instaling the latest package from github instead of the pub.dev package:
`# connectivity_plus: ^4.0.2
  connectivity_plus:
    git:
      url: git@github.com:fluttercommunity/plus_plugins.git
      path: packages/connectivity_plus/connectivity_plus
`

Now this temporary solution is working fine, while waiting for the package team to solve this issue.

**Comment by netease-george** [comment] 2023-10-07 03:22
same issue

**Comment by raqeta** [comment] 2023-10-07 06:02
you are great 😎 such a quick response and fix, thank you

**Comment by vbuberen** [comment] 2023-10-07 08:53
> Just wasted 4 days becuase of this package. it's working on debug mode with no issues, but craches the app in release mode.
The package was working fine, but after I updated xCode to the latest version that supports iOS 17, the app started crashing immediatly after launching it on iOS versions before iOS 17, but it is working on iOS 17.

You could use search in already opened issues in the first place and we wouldn't have to hear stories about `wasted 4 days`.
There is literally a checkbox that you marked that you did search, while it is definitely a lie as it seems. Closing as another duplicate of other issues where it was explicitly mentioned that there will be a fix released on pub.dev and in the meantime you can use version from `main`.

**Closed by vbuberen** 2023-10-07 08:53 UTC
Labels: bug, duplicate

**Comment by HamzaMihfad** [comment] 2023-10-07 09:12
I'm sorry to let you know that it's not a lie, and many people are affected by this issue.
As you can see the app started craching on 3 october, and I didn't fix the issue until yesterday, waiting for apple to accept the update.

<img width="1458" alt="Screenshot 2023-10-07 at 10 08 29" src="https://github.com/fluttercommunity/plus_plugins/assets/53432751/94a00a7b-6aee-4c3d-a595-f540acdcd411">

**Comment by HamzaMihfad** [comment] 2023-10-07 09:13
@vbuberen I'm sorry to let you know that it's not a lie, and many people are affected by this issue.
As you can see the app started craching on 3 october, and I didn't fix the issue until yesterday, waiting for apple to accept the update.

<img width="1458" alt="Screenshot 2023-10-07 at 10 08 29" src="https://github.com/fluttercommunity/plus_plugins/assets/53432751/94a00a7b-6aee-4c3d-a595-f540acdcd411">

**Comment by vbuberen** [comment] 2023-10-07 09:15
> I'm sorry to let you know that it's not a lie, and many people are affected by this issue.

Lie is not the issue, but that you tried to search the issue here in the repo before opening yours. 
Doesn't matter as there will be a fix anyway.
