### ISSUE TITLE
[package_info_plus] version and buildnumber is 1.0.0.

### ISSUE THREAD

**Issue by SergejSachs** [fluttercommunity/plus_plugins#716] opened 2022-01-30 15:28 UTC
I can get the version and build number on every platform **except windows**.

```
Future<void> _getAppInfo(Emitter<AppinfoState> emit) async {
    emit(AppinfoLoading());

    packageInfo = await PackageInfo.fromPlatform();

    emit(AppinfoLoaded(packageInfo.version, packageInfo.buildNumber));
  }
```
In case of windows I get 1.0.0 as the version and empty as build number.

pubspec.yaml
`version: 1.1.157+190`

This happens in debug mode, for a executable and if I create a MSIX package as well.

**Comment by marcov-dart** [comment] 2022-02-02 06:56
The plugin does work, but unfortuantly the build number for windows is in Windows\runner\Runner.rc (VERSION_AS_NUMBER and VERSION_AS_STRING) and flutter does not update this when the version in pubspec.yaml is changed.

**Comment by fabiancrx** [comment] 2022-04-05 17:55
@jpnurmi this is a possible duplicate of #343,  maybe progress could be tracked on that issue?

**Closed** 2022-04-05 20:17 UTC
Labels: bug
