### ISSUE TITLE
Support for command line apps

### ISSUE THREAD

**Issue by jlubeck** [fluttercommunity/plus_plugins#41] opened 2020-11-05 17:15 UTC
## Use case

Trying to create a `-v` flag for my command line application, and when I `import 'package:package_info_plus/package_info_plus.dart';` I'm getting these errors:

```
../../../flutter/packages/flutter/lib/src/services/binary_messenger.dart:7:8: Error: Not found: 'dart:ui'
import 'dart:ui' as ui;
       ^
../../../flutter/packages/flutter/lib/src/services/binding.dart:8:8: Error: Not found: 'dart:ui'
import 'dart:ui' as ui;
       ^
../../../flutter/packages/flutter/lib/src/services/font_loader.dart:7:8: Error: Not found: 'dart:ui'
import 'dart:ui';
       ^
../../../flutter/packages/flutter/lib/src/services/platform_messages.dart:7:8: Error: Not found: 'dart:ui'
import 'dart:ui' as ui;
       ^
../../../flutter/packages/flutter/lib/src/services/platform_views.dart:7:8: Error: Not found: 'dart:ui'
import 'dart:ui';
       ^
../../../flutter/packages/flutter/lib/src/services/raw_keyboard.dart:6:8: Error: Not found: 'dart:ui'
import 'dart:ui';
       ^
../../../flutter/packages/flutter/lib/src/services/system_channels.dart:6:8: Error: Not found: 'dart:ui'
import 'dart:ui';
       ^
../../../flutter/packages/flutter/lib/src/services/system_chrome.dart:7:8: Error: Not found: 'dart:ui'
import 'dart:ui';
       ^
../../../flutter/packages/flutter/lib/src/services/system_chrome.dart:13:1: Error: Not found: 'dart:ui'
export 'dart:ui' show Brightness;
^
../../../flutter/packages/flutter/lib/src/services/text_editing.dart:6:8: Error: Not found: 'dart:ui'
import 'dart:ui' show hashValues, TextAffinity, TextPosition, TextRange;
       ^
```

Which makes sense because command line apps don't have the `dart:ui`library

## Proposal

It would be great to be able to get my pubspec version from my command line app, like I do on my other apps.

Thanks!

**Comment by jpnurmi** [comment] 2020-11-05 17:35
It might be tricky because the default implementation of federated plugins is based on `MethodChannel` from `flutter/services`, which depends on `dart:ui`:
```
$ git grep "import 'dart:ui'" packages/flutter/lib/src/services/
packages/flutter/lib/src/services/binary_messenger.dart:import 'dart:ui' as ui;
packages/flutter/lib/src/services/binding.dart:import 'dart:ui' as ui;
packages/flutter/lib/src/services/font_loader.dart:import 'dart:ui';
packages/flutter/lib/src/services/platform_messages.dart:import 'dart:ui' as ui;
packages/flutter/lib/src/services/platform_views.dart:import 'dart:ui';
packages/flutter/lib/src/services/raw_keyboard.dart:import 'dart:ui';
packages/flutter/lib/src/services/system_channels.dart:import 'dart:ui';
packages/flutter/lib/src/services/system_chrome.dart:import 'dart:ui';
packages/flutter/lib/src/services/text_editing.dart:import 'dart:ui' show hashValues, TextAffinity, TextPosition, TextRange;
packages/flutter/lib/src/services/text_input.dart:import 'dart:ui' show
```

**Comment by jlubeck** [comment] 2020-11-05 17:37
Is there a repo for `federated plugins` where I might raise this up?

**Comment by jpnurmi** [comment] 2020-11-05 18:29
I think federated plugins itself are not a problem because it's just a way to split up platform specific implementations to separate packages.

The problem is more like the way Flutter communicates with platforms over method channels, and that this particular functionality is in a UI-dependent library. I believe all app-facing and platform-interface packages in Plus Plugins depend on method channels because that is the way to communicate with native Android and iOS code, for example. There are only a few exceptions (some Dart only platform plugins) that do not require method channels.

**Comment by stuartmorgan** [comment] 2020-11-07 15:57
I think there's a fundamental misunderstand about plugins here. Packages are a Dart concept, but plugin packages (commonly just called plugins) are [a Flutter concept](https://flutter.dev/docs/development/packages-and-plugins/developing-packages#plugin). A command line Dart application isn't a Flutter application, so Flutter plugins are not applicable at all.

It's not just the Dart method channel code. The metadata that identifies implementations? Flutter-specific. The tooling that builds and links the native code? Part of the `flutter` tool. The system that delivers messages to that native code? Part of the Flutter engine. The codecs that interpret those messages on the native side? Part of the Flutter SDK.

Someone could potentially make a package to get metadata for a command line Dart application (although you'd have to figure out how to embed it in the binary) but it wouldn't be a plugin, and it would look almost nothing like `package_info_plus`.

**Comment by jpnurmi** [comment] 2020-11-17 22:11
I'm closing this because there's not much we can do here.

**Closed by jpnurmi** 2020-11-17 22:11 UTC
Labels: enhancement
