### ISSUE TITLE
[Request]: Because package_info_plus >=4.0.0 depends on http ^0.13.5 and xxx depends on http ^1.0.0

### ISSUE THREAD

**Issue by cnkygmr** [fluttercommunity/plus_plugins#1854] opened 2023-05-25 13:17 UTC
### Plugin

package_info_plus

### Use case

Because package_info_plus >=4.0.0 depends on http ^0.13.5 and xxx depends on http ^1.0.0, package_info_plus >=4.0.0 is forbidden.
So, because xxx depends on package_info_plus ^4.0.1, version solving failed.

### Proposal

Upgrade to new version

**Comment by vbuberen** [comment] 2023-05-25 13:36
Duplicate of #1840 which is already resolved and will be available in a next release.

**Comment by admonxetrii** [comment] 2023-05-28 15:14
I did search on google and seems your package doesn't support google_fonts ^4.0.5

**Comment by vbuberen** [comment] 2023-05-28 17:19
> I did search on google and seems your package doesn't support google_fonts ^4.0.5
> 

I believe you should read how dependency resolution happens, especially when there are versioning issues https://docs.flutter.dev/packages-and-plugins/using-packages#conflict-resolution
There is no connection with 'google_fonts' package.

**Comment by vbuberen** [comment] 2023-05-29 12:23
Just published a new version of `package_info_plus` with relaxed constraints, so users now free to use either pre 1.0 `http` or 1.0 and onwards. Check our 4.0.2 version of `package_info_plus`.

Closing a completed.

**Closed by vbuberen** 2023-05-29 12:23 UTC
Labels: enhancement
