### ISSUE TITLE
[Bug]: Could not find kotlin-util-klib-1.7.22.jar (org.jetbrains.kotlin:kotlin-util-klib:1.7.22).

### ISSUE THREAD

**Issue by alok2811** [fluttercommunity/plus_plugins#1990] opened 2023-07-29 09:41 UTC
### Platform

Android 12

### Plugin

package_info_plus

### Version

^4.0.2

### Flutter SDK

3.10.6

### Steps to reproduce

1. I upgraded my android studio then I try to build apk following issues showed on log and not able to build apk
2. I try with a new project to add same pacakage show same error

Android Studio: Android Studio Giraffe | 2022.3.1
Flutter : 03.10.6

### Code Sample

```dart
The sample code not show any error coming when I build or run the project
```

### Logs

```shell
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':package_info_plus'.
> Could not resolve all files for configuration ':package_info_plus:classpath'.
   > Could not find kotlin-util-klib-1.7.22.jar (org.jetbrains.kotlin:kotlin-util-klib:1.7.22).
     Searched in the following locations:
         https://maven.aliyun.com/repository/jcenter/org/jetbrains/kotlin/kotlin-util-klib/1.7.22/kotlin-util-klib-1.7.22.jar
   > Could not find kotlin-annotation-processing-gradle-1.7.22.jar (org.jetbrains.kotlin:kotlin-annotation-processing-gradle:1.7.22).
     Searched in the following locations:
         https://maven.aliyun.com/repository/jcenter/org/jetbrains/kotlin/kotlin-annotation-processing-gradle/1.7.22/kotlin-annotation-processing-gradle-1.7.22.jar
   > Could not find kotlin-build-common-1.7.22.jar (org.jetbrains.kotlin:kotlin-build-common:1.7.22).
     Searched in the following locations:
         https://maven.aliyun.com/repository/jcenter/org/jetbrains/kotlin/kotlin-build-common/1.7.22/kotlin-build-common-1.7.22.jar
> Failed to notify project evaluation listener.
   > Could not get unknown property 'android' for project ':package_info_plus' of type org.gradle.api.Project.
   > Could not get unknown property 'android' for project ':package_info_plus' of type org.gradle.api.Project.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
Exception: Gradle task assembleDebug failed with exit code 1
```

### Flutter Doctor

```shell
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.4.1 22F770820d darwin-arm64,
    locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.80.1)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
alokdubey@192 ~ %
```

### Checklist before submitting a bug

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by nohli** [comment] 2023-07-29 11:13
Please paste the output of `flutter doctor -v`.

Have you installed the Android SDK?

**Comment by alok2811** [comment] 2023-07-29 11:18
@nohli 

alokdubey@192 ~ % flutter doctor -v
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.4.1 22F770820d darwin-arm64,
    locale en-IN)
    • Flutter version 3.10.6 on channel stable at /Users/alokdubey/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (2 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/alokdubey/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.80.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.68.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 12
      (API 31) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS
      13.4.1 22F770820d darwin-arm64
    • Chrome (web)                • chrome        • web-javascript • Google
      Chrome 115.0.5790.114

[✓] Network resources
    • All expected network resources are available.

• No issues found!

**Comment by vbuberen** [comment] 2023-07-29 17:40
> https://maven.aliyun.com/repository/jcenter

It is strange that Kotlin was searched only in this specific Maven repo. You specified some specific repositories in Android `build.gradle`?
Please check that your `build.gradle` file contains Maven Central as well, so your `repositories` block looks like something like this:
```
repositories {
        google()
        mavenCentral()
    }
```

**Comment by alok2811** [comment] 2023-07-29 17:54
<img width="1440" alt="Screenshot 2023-07-29 at 11 21 47 PM" src="https://github.com/fluttercommunity/plus_plugins/assets/72010020/a459270f-cf41-4f11-9cde-05a0f07711db">

@vbuberen it added if anywhere else needs to change please let me know

**Comment by nohli** [comment] 2023-07-29 19:40
FYI You don't need to tag people already involved in this conversation.

It says

```
Could not get unknown property 'android' for project ':package_info_plus' of type org.gradle.api.Project.
```

So there seems to be a general issue on your end. Can you please reply to my questions from [earlier](https://github.com/fluttercommunity/plus_plugins/issues/1990#issuecomment-1656707249)?

Try `flutter clean`, `flutter pub get` and `flutter build apk`.

Try opening only the android folder in Android studio and performing a gradle sync, also try `Build` - `clean project`.

Please share a screenshot of `File` - `Project structure`, where it shows the AGP and Gradle version.

Also please share your `app/build.gradle`, `build.gradle` and `gradle/wrapper/gradle-wrapper.properties` (can wrap each one in ``` to format as code).

I think, we will figure it out soon 🤗

**Comment by alok2811** [comment] 2023-07-29 20:06
Finally, after 15 hours, I resolve this bug by following the changes

1. In my Flutter project  I go External Libraries => Flutter Plugins => package_info_plus => android => build.gradle 
2. and  give permission to edit this file and make following changes 
 
`    repositories {
        google()
        mavenCentral()  // move it from bottom to top
        maven { url 'https://maven.aliyun.com/repository/jcenter' }
        maven { url 'https://maven.aliyun.com/repository/central' }
        maven { url 'https://maven.aliyun.com/repository/google' }
        maven { url 'https://maven.aliyun.com/repository/public' }
        maven { url 'https://maven.aliyun.com/repository/gradle-plugin' }

    }`

`rootProject.allprojects {
    repositories {
        google()
        mavenCentral() // move it from bottom to top
        maven { url 'https://maven.aliyun.com/repository/jcenter' }
        maven { url 'https://maven.aliyun.com/repository/central' }
        maven { url 'https://maven.aliyun.com/repository/google' }
        maven { url 'https://maven.aliyun.com/repository/public' }
        maven { url 'https://maven.aliyun.com/repository/gradle-plugin' }

    }
}`


I don't know what will happen but its working for me 

Thank you @nohli  @vbuberen  really appreciate your efforts

**Comment by nohli** [comment] 2023-07-29 20:17
Congrats!

It seems you were [not the only one](https://github.com/fluttercommunity/plus_plugins/issues?q=Could+not+get+unknown+property+%27android%27) with a problem like this.

**Comment by vbuberen** [comment] 2023-07-29 20:41
I am curios how it happened that you have all these `aliyun` mirrors of Maven in the first place. You specified them somewhere in the project?

**Comment by alok2811** [comment] 2023-07-29 20:52
Its already added in this i just move this  bottom to top 

    ```
 google()
        mavenCentral() // move it from bottom to top``
```

**Comment by nohli** [comment] 2023-07-29 20:56
`and give permission to edit this file and make following changes` - so you had to edit `package_info_plus`'s code. What version is in your pubspec.lock?

**Comment by alok2811** [comment] 2023-07-29 20:59
pubspec.yaml 
`package_info_plus: ^4.0.2`

pubspec.lock
```
  package_info_plus:
    dependency: "direct main"
    description:
      name: package_info_plus
      sha256: ceb027f6bc6a60674a233b4a90a7658af1aebdea833da0b5b53c1e9821a78c7b
      url: "https://pub.dev"
    source: hosted
    version: "4.0.2"
  package_info_plus_platform_interface:
    dependency: transitive
    description:
      name: package_info_plus_platform_interface
      sha256: "9bc8ba46813a4cc42c66ab781470711781940780fd8beddd0c3da62506d3a6c6"
      url: "https://pub.dev"
    source: hosted
    version: "2.0.1"
```

**Comment by nohli** [comment] 2023-07-29 21:16
Did you specify `maven { url 'https://maven.aliyun.com/repository` anywhere else in your project (could search all files in the directory), like in an `init.gradle`?

**Comment by vbuberen** [comment] 2023-08-23 10:48
Closing as the issue is resolved and no further activity here.

**Closed by vbuberen** 2023-08-23 10:48 UTC
Labels: bug, triage
