### ISSUE TITLE
[Bug]:  Unable to build my project after adding share_plus 

### ISSUE THREAD

**Issue by casontek** [fluttercommunity/plus_plugins#2858] opened 2024-04-26 17:02 UTC
### Platform

Android 12

### Plugin

share_plus

### Version

9.0.0

### Flutter SDK

3.22.0-18.0.pre.30 

### Steps to reproduce

I created an empty flutter project and it successfully built and runned.
And after adding share_plus pligins, it stopped building 

### Code Sample

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}





//settings.gradle
pluginManagement {
    def flutterSdkPath = {
        def properties = new Properties()
        file("local.properties").withInputStream { properties.load(it) }
        def flutterSdkPath = properties.getProperty("flutter.sdk")
        assert flutterSdkPath != null, "flutter.sdk not set in local.properties"
        return flutterSdkPath
    }()

    includeBuild("$flutterSdkPath/packages/flutter_tools/gradle")

    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

plugins {
    id "dev.flutter.flutter-plugin-loader" version "1.0.0"
    id "com.android.application" version "7.3.0" apply false
    id "org.jetbrains.kotlin.android" version "1.7.10" apply false
}

include ":app"




//build.gradle
allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}



//app/build.gradle
plugins {
    id "com.android.application"
    id "kotlin-android"
    // The Flutter Gradle Plugin must be applied after the Android and Kotlin Gradle plugins.
    id "dev.flutter.flutter-gradle-plugin"
}

android {
    namespace = "com.example.flutterapptext"
    compileSdk = 34 //flutter.compileSdkVersion
    ndkVersion = flutter.ndkVersion

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId = "com.example.flutterapptext"
        // You can update the following values to match your application needs.
        // For more information, see: https://docs.flutter.dev/deployment/android#reviewing-the-gradle-build-configuration.
        minSdk = 29 //flutter.minSdkVersion
        targetSdk = 34 //flutter.targetSdkVersion
        versionCode = flutter.versionCode
        versionName = flutter.versionName
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig = signingConfigs.debug
        }
    }
}

flutter {
    source = "../.."
}
```

### Logs

```shell
* What went wrong:
Execution failed for task ':share_plus:compileDebugJavaWithJavac'.
> error: invalid source release: 17

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 1s
Error: Gradle task assembleDebug failed with exit code 1
```

### Flutter Doctor

```shell
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 3.22.0-18.0.pre.30, on macOS 13.5 22G74 darwin-x64,
    locale en-NG)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.
[!] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    ! Flutter recommends a minimum Xcode version of 15.
      Download the latest version or update via the Mac App Store.
    ! CocoaPods 1.12.1 out of date (1.13.0 is recommended).
        CocoaPods is a package manager for iOS or macOS platform code.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To update CocoaPods, see
      https://guides.cocoapods.org/using/getting-started.html#updating-cocoapods
[✓] Chrome - develop for the web
[!] Android Studio (version unknown)
    ✗ Unable to determine Android Studio version.
[✓] Android Studio (version 2022.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.3.2)
[✓] VS Code (version 1.82.2)
[✓] Connected device (3 available)
[✓] Network resources
```

### Checklist before submitting a bug

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by ramonpaolo** [comment] 2024-04-27 00:36
I have the same problem!

I update the share_plus to 9.0.0 in my flutter project, and it stop to building!

```
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':share_plus:compileReleaseJavaWithJavac'.
```

In my case, I use the flutter v3.19.6

**Comment by ramonpaolo** [comment] 2024-04-27 01:45
I solve this updating the java version to the 17!

In my case, it was the solution:
```yaml
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'
```

**Comment by casontek** [comment] 2024-04-27 07:18
Hi Ramon,

Did you write that inside pubspec.yaml file.
Or is there another setup file.

**Comment by bymomo** [comment] 2024-04-27 07:53
> 我解决了这个问题，将 java 版本更新到 17！
> 
> 就我而言，这是解决方案：
> 
> ```yaml
>       - name: Setup Java
>         uses: actions/setup-java@v2
>         with:
>           distribution: 'zulu'
>           java-version: '17'
> ```

This is not effective for me. I just introduced share_plus: ^ 9.0.0 in pubspec.yaml, my JDK version is 17, and my Gradle version is 7.3

**Comment by bymomo** [comment] 2024-04-27 07:54
> I solve this updating the java version to the 17!
> 
> In my case, it was the solution:
> 
> ```yaml
>       - name: Setup Java
>         uses: actions/setup-java@v2
>         with:
>           distribution: 'zulu'
>           java-version: '17'
> ```

This is not effective for me. I just introduced share_plus: ^ 9.0.0 in pubspec.yaml, my JDK version is 17, and my Gradle version is 7.3

**Comment by omidima** [comment] 2024-04-27 08:14
in this case currently, i rollback to version 7.0.0 and fixed this problem for now. we should wait to new update for fix this problem in version 8 and 9.

```ruby
dependencies:
      share_plus: ^7.0.0
```

**Comment by Seferi** [comment] 2024-04-28 13:27
I'm on package_info_plus 7.0.0 and getting the same error:

Execution failed for task ':package_info_plus:compileReleaseJavaWithJavac'.
> error: invalid source release: 17

Android section on build.gradle:

android {
    namespace "org.keyoxide.keyoxide_flutter"
    compileSdkVersion 34

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        applicationId "org.example.app"
        minSdkVersion 24
        targetSdkVersion 34
        compileSdkVersion 34
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

**Comment by vbuberen** [comment] 2024-04-28 19:59
> error: invalid source release: 17

@casontek The problem is stated explicitly in your logs. You need to use Java 17 as it is required by the plugin.

> in this case currently, i rollback to version 7.0.0 and fixed this problem for now. we should wait to new update for fix this problem in version 8 and 9.

@omidima This is the problem with your project setup, not the plugin, so don't spread false statements that mislead people.

> compileOptions {
>     sourceCompatibility JavaVersion.VERSION_1_8
>     targetCompatibility JavaVersion.VERSION_1_8
> }
> 
> kotlinOptions {
>     jvmTarget = '1.8'
> }

@Seferi Now compare it with the example app of the plugin to see the difference and understand that you set Java 8 in your version, while the plugin requires Java 17.

Closing as this is not a bug. Read the documentation and switch your projects to use Java 17. There is an example project for a reason if you need an `example`

**Closed by vbuberen** 2024-04-28 19:59 UTC
Labels: bug, triage
