### ISSUE TITLE
[Share_plus] Ipad not working

### ISSUE THREAD

**Issue by kjawadDeveloper** [fluttercommunity/plus_plugins#870] opened 2022-05-25 04:44 UTC
Share plus plugin version 4.0.4 is not working on IPAD while working on android correctly.

**Comment by daniellai** [comment] 2022-05-31 00:09
I tested share_plus 4.0.4 on an iPad simulator (software version 15.5) and a physical iPad device (software version 15.3.1), after executing Share.share('some text'), there was no response.  The same code worked well on an iPhone simulator.

**Comment by miquelbeltran** [comment] 2022-05-31 13:33
Please use the Bug template to fill a bug report and include all the information in it

**Comment by miquelbeltran** [comment] 2022-06-01 06:04
Maybe the documentation helps?

```
  /// The optional [sharePositionOrigin] parameter can be used to specify a global
  /// origin rect for the share sheet to popover from on iPads. It has no effect
  /// on non-iPads.
```

**Comment by krillefear** [comment] 2022-06-04 18:20
I'm getting the same error. Any workaround or fix out there? This blocks all of my apps from a new release...

**Comment by miquelbeltran** [comment] 2022-06-06 07:54
It works for me. See screenshot.

Can you provide a code sample that fails for you?

![image](https://user-images.githubusercontent.com/2494376/172119336-bdbd21e0-bf41-4398-993d-3cbce1dd8c6c.png)

**Comment by XRayAdamo** [comment] 2022-06-26 01:33
Same error on 4.07 version
`[LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
	(Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSAutoresizingMaskLayoutConstraint:0x280def610 h=-&- v=--& _UIActivityContentNavigationBar:0x15dd9f010.minY == 0   (active, names: '|':UILayoutContainerView:0x15dd9ee80 )>",
    "<NSAutoresizingMaskLayoutConstraint:0x280deed50 h=-&- v=--& _UIActivityContentNavigationBar:0x15dd9f010.height == 50   (active)>",
    "<NSLayoutConstraint:0x280d8a9e0 V:[_UIActivityContentNavigationBar:0x15dd9f010]-(0)-[UIFocusContainerGuide:0x2811d8c30'UINavigationControllerContentFocusContainerGuide']   (active)>",
    "<NSLayoutConstraint:0x280d8aad0 UIFocusContainerGuide:0x2811d8c30'UINavigationControllerContentFocusContainerGuide'.bottom == UILayoutContainerView:0x15dd9ee80.bottom   (active)>",
    "<NSLayoutConstraint:0x280ded090 V:|-(0)-[UILayoutContainerView:0x15dd9ee80]   (active, names: '|':UIView:0x15dd95160 )>",
    "<NSLayoutConstraint:0x280decb90 UILayoutContainerView:0x15dd9ee80.bottom == UIView:0x15dd95160.bottom   (active)>",
    "<NSLayoutConstraint:0x280deec10 'UIView-Encapsulated-Layout-Height' UIView:0x15dd95160.height == 0   (active)>"
)


Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x280d8a9e0 V:[_UIActivityContentNavigationBar:0x15dd9f010]-(0)-[UIFocusContainerGuide:0x2811d8c30'UINavigationControllerContentFocusContainerGuide']   (active)>


Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
[Default] Task Runner[53205]/1#3 LF=0 couldn't find entitlement CopresenceCore.Entitlement.publicAPI error nil
[LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x280d87cf0 H:|-(0)-[_UIActivityContentTitleView:0x1602215c0]   (active, names: '|':_UINavigationBarContentView:0x15dda01c0 )>",
    "<NSLayoutConstraint:0x280d87d90 _UIActivityContentTitleView:0x1602215c0.trailing == _UINavigationBarContentView:0x15dda01c0.trailing   (active)>",
    "<NSLayoutConstraint:0x280de5d10 LPLinkView:0x1602149e0.leading == UILayoutGuide:0x2817d3100'UIViewLayoutMarginsGuide'.leading   (active)>",
    "<NSLayoutConstraint:0x280de5c70 LPLinkView:0x1602149e0.trailing == UILayoutGuide:0x2817d3100'UIViewLayoutMarginsGuide'.trailing   (active)>",
    "<NSLayoutConstraint:0x280dee9e0 'UIView-Encapsulated-Layout-Width' _UINavigationBarContentView:0x15dda01c0.width == 6   (active)>",
    "<NSLayoutConstraint:0x280defde0 'UIView-leftMargin-guide-constraint' H:|-(29)-[UILayoutGuide:0x2817d3100'UIViewLayoutMarginsGuide'](LTR)   (active, names: '|':_UIActivityContentTitleView:0x1602215c0 )>",
    "<NSLayoutConstraint:0x280defd90 'UIView-rightMargin-guide-constraint' H:[UILayoutGuide:0x2817d3100'UIViewLayoutMarginsGuide']-(8)-|(LTR)   (active, names: '|':_UIActivityContentTitleView:0x1602215c0 )>"
)


Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x280de5c70 LPLinkView:0x1602149e0.trailing == UILayoutGuide:0x2817d3100'UIViewLayoutMarginsGuide'.trailing   (active)>


Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
`

and code is just a code
`await Share.shareFiles([path], mimeTypes: ['image/png']);`

I've been trying to add **sharePositionOrigin** and it didn't help. Fails on iPad simulator and physical device, but working on iPhones

**Comment by miquelbeltran** [comment] 2022-06-27 06:25
> Without providing sharePositionOrigin it will not work. 

Of course not, you have to provide this parameter on iPads, it is explained in the documentation

**Comment by jamesncl** [comment] 2022-07-29 14:01
I'm also experiencing this error on iPad, and I'm providing the sharePositionOrigin:

```
final box = context.findRenderObject() as RenderBox?;

Share.shareFiles(
  [file.path],
  mimeTypes: ['application/pdf'],
  // share_plus requires iPad users to provide the sharePositionOrigin parameter.
  // Without it, share_plus will not work on iPads and may cause a crash or letting the UI not responding.
  sharePositionOrigin: box!.localToGlobal(Offset.zero) & box.size,
);
```

**Comment by miquelbeltran** [comment] 2022-07-31 12:55
@jamesncl which `context` are you using? 

Can you provide the full code sample?

**Comment by matszafraniec** [comment] 2022-08-10 11:59
Hello,

On my side, when provided sharePositionOrigin as `box!.localToGlobal(Offset.zero) & box.size` in landscape mode on iPad it presents Share dialog out of my view. I switched it to `box!.localToGlobal(Offset(context.width, 0)) & box.size` and it works fine now: Share dialog is presented in the middle of the screen. Please note that in my app share option is called from application bar.

So if you don't face any errors, you have to manipulate with Offset value to display your Share dialog.

**Comment by expertdev-designer** [comment] 2022-09-13 11:46
I am using  share_plus 4.1.0 on an iPhone 7  after executing Share.share('deeplink with socialMetaTagParameters for preview ')
 
deep link:  https://firebase.google.com/docs/dynamic-links/flutter/create

It's working fine for WhatsApp when i shared but not for  skype
![image_2022_09_13T11_21_00_470Z](https://user-images.githubusercontent.com/52417551/189892634-1d2618cf-4f7c-4dfd-a828-d57ba46a4342.png)
Logs: 

[LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x28004d3b0 _UIActivityActionCellTitleLabel:0x159c5ae50.height >= 27.5   (active)>",
    "<NSLayoutConstraint:0x280047570 V:|-(15)-[_UIActivityActionCellTitleLabel:0x159c5ae50]   (active, names: '|':UIView:0x159c5ba50 )>",
    "<NSLayoutConstraint:0x2800b12c0 V:[_UIActivityActionCellTitleLabel:0x159c5ae50]-(15)-|   (active, names: '|':UIView:0x159c5ba50 )>",
    "<NSLayoutConstraint:0x28004f7a0 'UIView-Encapsulated-Layout-Height' UIView:0x159c5ba50.height == 52   (active)>"
)


Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x28004d3b0 _UIActivityActionCellTitleLabel:0x159c5ae50.height >= 27.5   (active)>


Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.

**Comment by expertdev-designer** [comment] 2022-09-13 11:47
@miquelbeltran @daniellai @tarja77 @jamesncl Please check what's issue

**Comment by miquelbeltran** [comment] 2022-09-14 06:42
> It's working fine for WhatsApp when i shared but not for skype

If it is working fine on some apps but not on one specific app, to me, it looks like a specific problem of that app and not on the plugin side

**Comment by expertdev-designer** [comment] 2022-09-14 07:23
@miquelbeltran how this issue from app side

Logs:

[LayoutConstraints] Unable to simultaneously satisfy constraints.
Probably at least one of the constraints in the following list is one you don't want.
Try this:
(1) look at each constraint and try to figure out which you don't expect;
(2) find the code that added the unwanted constraint or constraints and fix it.
(
"<NSLayoutConstraint:0x28004d3b0 _UIActivityActionCellTitleLabel:0x159c5ae50.height >= 27.5 (active)>",
"<NSLayoutConstraint:0x280047570 V:|-(15)-[_UIActivityActionCellTitleLabel:0x159c5ae50] (active, names: '|':UIView:0x159c5ba50 )>",
"<NSLayoutConstraint:0x2800b12c0 V:[_UIActivityActionCellTitleLabel:0x159c5ae50]-(15)-| (active, names: '|':UIView:0x159c5ba50 )>",
"<NSLayoutConstraint:0x28004f7a0 'UIView-Encapsulated-Layout-Height' UIView:0x159c5ba50.height == 52 (active)>"
)

Will attempt to recover by breaking constraint
<NSLayoutConstraint:0x28004d3b0 _UIActivityActionCellTitleLabel:0x159c5ae50.height >= 27.5 (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.

**Comment by miquelbeltran** [comment] 2022-09-14 07:46
> Unable to simultaneously satisfy constraints.

This has been documented in the README.md, when using the share_plus on iPad the `sharePositionOrigin` must be provided, and this needs to be correct. If you are not provided sample code showing how you exactly calculate this value we cannot help you.

**Comment by expertdev-designer** [comment] 2022-09-14 08:24
@miquelbeltran i tested with this as well sharePositionOrigin
but not fixed ..Let me share sample code with you

**Comment by expertdev-designer** [comment] 2022-09-14 08:58
Hii @miquelbeltran  Please look into this ..it's urgent
i am using   share_plus: ^4.1.0
```
Flutter (Channel stable, 2.10.5, on macOS 11.6.5 20G527 darwin-x64, locale en-GB)
    • Flutter version 2.10.5 at /Users/elintminds/Documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (5 months ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/elintminds/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] Connected device (3 available)
    • Elint’s iPhone (mobile)    • caeedac25a54fc67101807449f92effc8f753851 • ios            • iOS 14.7.1 18G82
    • iPhone 13 Pro Max (mobile) • 5C849666-2ACD-4315-8822-D1C3E96DA04A     • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • Chrome (web)               • chrome                                   • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
sample code:
```
void _shareNews(BuildContext context)  {
    String _shareMessage =
    '''check out: Naira appreciates 0.10% against dollar at official market. Visit https://www.ripplesnigeria.com/naira-appreciates-0-10-against-dollar-at-official-market/  to get more details.''';
    try {
      final box = context.findRenderObject() as RenderBox?;
      Share.share(_shareMessage,  sharePositionOrigin: box!.localToGlobal(Offset.zero) & box.size,
      );
    } catch (e) {
      debugPrint('${e.toString()}');
    }
  }
```

Log :
```

[LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x283ca7a20 _UIActivityActionCellTitleLabel:0x15c10b6b0.height >= 27.5   (active)>",
    "<NSLayoutConstraint:0x283ca5c70 V:|-(15)-[_UIActivityActionCellTitleLabel:0x15c10b6b0]   (active, names: '|':UIView:0x15c11e260 )>",
    "<NSLayoutConstraint:0x283ca7bb0 V:[_UIActivityActionCellTitleLabel:0x15c10b6b0]-(15)-|   (active, names: '|':UIView:0x15c11e260 )>",
    "<NSLayoutConstraint:0x283ca79d0 'UIView-Encapsulated-Layout-Height' UIView:0x15c11e260.height == 52   (active)>"
)


Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x283ca7a20 _UIActivityActionCellTitleLabel:0x15c10b6b0.height >= 27.5   (active)>


Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.


```

**Comment by miquelbeltran** [comment] 2022-09-14 08:58
```
void _shareNews(BuildContext context)  {
```

Where are you getting this context from?

**Comment by expertdev-designer** [comment] 2022-09-14 09:01
@miquelbeltran  from Widget build(BuildContext context) {

**Comment by miquelbeltran** [comment] 2022-09-14 09:05
So that's probably wrong, and you are not providing a valid Rect in the sharePositionOrigin.

If you look at the example main.dart you will see that the share call is wrapped with a Builder, and it is not using the context from the top widget.

You need to understand what your code does, rather than copying code and complaining that things don't work.

**Comment by miquelbeltran** [comment] 2022-09-14 09:08
I am closing this issue now, if you have a problem providing the sharePositionOrigin, run the example in the project and see if you can reproduce the issue. If the example works, but your code doesn't, then there's a bug in your code.

**Closed by miquelbeltran** 2022-09-14 09:08 UTC
Labels: bug, share_plus, iPadOs, missing info
