### ISSUE TITLE
android_alarm_manager_plus 1.2.0 Unhandled Exception

### ISSUE THREAD

**Issue by spacekestrel** [fluttercommunity/plus_plugins#446] opened 2021-09-04 09:35 UTC
Upon adding this line:
```
 await AndroidAlarmManager.initialize();
```
 flutter gives this message:
```
E/flutter ( 3632): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Null check operator used on a null value
E/flutter ( 3632): #0      MethodChannel.binaryMessenger
package:flutter/…/services/platform_channel.dart:121
E/flutter ( 3632): #1      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:146
E/flutter ( 3632): #2      MethodChannel.invokeMethod
package:flutter/…/services/platform_channel.dart:329
E/flutter ( 3632): #3      AndroidAlarmManager.initialize
package:android_alarm_manager_plus/android_alarm_manager_plus.dart:99
E/flutter ( 3632): #4      main
package:test_alarm/main.dart:6
E/flutter ( 3632): #5      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:145:25)
E/flutter ( 3632): #6      _rootRun (dart:async/zone.dart:1428:13)
E/flutter ( 3632): #7      _CustomZone.run (dart:async/zone.dart:1328:19)
E/flutter ( 3632): #8      _runZoned (dart:async/zone.dart:1863:10)
E/flutter ( 3632): #9      runZonedGuarded (dart:async/zone.dart:1851:12)
E/flutter ( 3632): #10     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:141:5)
E/flutter ( 3632): #11     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
E/flutter ( 3632): #12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
E/flutter ( 3632):
```

**Comment by JamiuJimoh** [comment] 2021-10-01 15:18
Can I work on this? @mhadaily

**Comment by ScottishRoss** [comment] 2021-10-01 15:53
@mhadaily I may have a solution for this. There was another issue that I can no longer find that was related to this. All I need is some advice on how to set get everything set up so I can package the PR together.

**Comment by mhadaily** [comment] 2021-10-01 17:57
@JamiuJimoh  and @ScottishRoss  can you both work on this and see if you have a similar solution ? you may continue here in the comments.

**Comment by JamiuJimoh** [comment] 2021-10-01 21:40
Alright. @ScottishRoss let's do this

**Comment by ScottishRoss** [comment] 2021-10-02 11:13
@JamiuJimoh Awesome! So what I did is I made all instances of BinaryMessenger nullable, then in platform_channel.dart (line 150) I modified _invokeMethod to check if binaryMessenger is null:

`Future<T?> _invokeMethod<T>(String method,
      {required bool missingOk, dynamic arguments}) async {
    assert(method != null);
    if (binaryMessenger != null) {
      final ByteData? result = await binaryMessenger!.send(
        name,
        codec.encodeMethodCall(MethodCall(method, arguments)),
      );
      if (result == null) {
        if (missingOk) {
          return null;
        }
        throw MissingPluginException(
            'No implementation found for method $method on channel $name');
      }
      return codec.decodeEnvelope(result) as T?;
    }
  }`
  
  I'm not too sure of this solution, truthfully. But it appears BinaryMessenger can be null at the start, which is why this is happening. 
  
 Another solution was to add WidgetsFlutterBinding.ensureInitialized(); to the start of my main().

**Comment by JamiuJimoh** [comment] 2021-10-02 21:45
@ScottishRoss i'm sorry for the late reply. I just got everything setup on my PC. I can't find the platform_channel.dart file.

**Comment by ScottishRoss** [comment] 2021-10-03 17:03
@JamiuJimoh Yeah, it's a Flutter file, so let's not do that! My bad.

**Comment by JamiuJimoh** [comment] 2021-10-03 17:30
Alright. I'll keep on debugging. I'll let you know when I find something. I'm checking where the error is coming from and then i'll check what's causing it.

**Comment by JamiuJimoh** [comment] 2021-10-03 22:14
@mhadaily I was able to run the example in the android_alarm_manager_plus yesterday.  Today I'm getting this error: 
`C:\Users\hyper\Development\plus_plugins\packages\android_alarm_manager_plus\android\src\main\java\dev\fluttercommunity\plus\androidalarmmanager\AlarmService.java:139: error: cannot find symbol
            (Build.VERSION >= 23 ? PendingIntent.FLAG_IMMUTABLE : 0)
             ^
  symbol:   variable Build
  location: class AlarmService
C:\Users\hyper\Development\plus_plugins\packages\android_alarm_manager_plus\android\src\main\java\dev\fluttercommunity\plus\androidalarmmanager\AlarmService.java:228: error: cannot find symbol
            (Build.VERSION >= 23 ? PendingIntent.FLAG_IMMUTABLE : 0)
`

**Comment by JamiuJimoh** [comment] 2021-10-03 22:23
@mhadaily I was able to run the example in the android_alarm_manager_plus yesterday. Today, I'm getting a compliation error: 

` error: cannot find symbol
            (Build.VERSION >= 23 ? PendingIntent.FLAG_IMMUTABLE : 0)
             ^
  symbol:   variable Build
  location: class AlarmService`

**Comment by ScottishRoss** [comment] 2021-10-04 10:10
@mhadaily This appears to be an issue with Flutter. The only solution I can see is to use WidgetsFlutterBinding.ensureInitialized(), which is what is used in the example. 

I don't think there can be a fix for this.

**Comment by miquelbeltran** [comment] 2021-10-04 11:50
Since the issue is unrelated to the package, is it fine to close this issue?

**Comment by JamiuJimoh** [comment] 2021-10-04 12:28
@miquelbeltran i think so

**Comment by ScottishRoss** [comment] 2021-10-04 12:38
@miquelbeltran I would say so. I would suggest adding my suggestion of WidgetsFlutterBinding.ensureInitialized() into the ReadMe.

**Closed** 2021-10-06 10:27 UTC
Labels: bug, android_alarm_manager_plus, Hacktoberfest
