### ISSUE TITLE
[Bug]: Device Info Plus not building anymore

### ISSUE THREAD

**Issue by FilledStacks** [fluttercommunity/plus_plugins#1000] opened 2022-08-08 07:06 UTC
### Platform

Android

### Plugin

device_info_plus

### Version

^3.2.3

### Flutter SDK

3.0.5

### Steps to reproduce

Try to run the app after doing `flutter pub upgrade`

I get the example. 

```
../../../../src/flutter/.pub-cache/hosted/pub.dartlang.org/device_info_plus_windows-2.1.1/lib/src/device_info_plus_windows.dart:24:35: Error: Required named parameter 'userName' must be provided.
    final data = WindowsDeviceInfo(
                                  ^
../../../../src/flutter/.pub-cache/hosted/pub.dartlang.org/device_info_plus_platform_interface-2.4.0/lib/model/windows_device_info.dart:12:3: Context: Found this candidate, but the arguments don't match.
  WindowsDeviceInfo({
  ^^^^^^^^^^^^^^^^^
```

### Logs

```shell
../../../../src/flutter/.pub-cache/hosted/pub.dartlang.org/device_info_plus_windows-2.1.1/lib/src/device_info_plus_windows.dart:24:35: Error: Required named parameter 'userName' must be provided.
    final data = WindowsDeviceInfo(
                                  ^
../../../../src/flutter/.pub-cache/hosted/pub.dartlang.org/device_info_plus_platform_interface-2.4.0/lib/model/windows_device_info.dart:12:3: Context: Found this candidate, but the arguments don't match.
  WindowsDeviceInfo({
  ^^^^^^^^^^^^^^^^^
```

### Flutter Doctor

```shell
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.3.1 21E258 darwin-arm, locale en-ZA)
    • Flutter version 3.0.5 at /Users/danemackier/src/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (4 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/danemackier/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.70.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (3 available)
    • SM G960F (mobile) • 2223cc1a36057ece • android-arm64  • Android 10 (API 29)
    • macOS (desktop)   • macos            • darwin-arm64   • macOS 12.3.1 21E258 darwin-arm
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 103.0.5060.134

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

**Comment by GauravCalidig** [comment] 2022-08-08 07:08
Stuck on same

![image](https://user-images.githubusercontent.com/90178033/183359684-1a69c349-d8f8-4773-9da1-57068d622627.png)

**Comment by FilledStacks** [comment] 2022-08-08 07:17
Anyone have a workaround yet? I'm trying to do dependency overrides but nothing is making it pass. 

If you find a version that works please post, I have an urgent build to get out.

**Comment by GauravCalidig** [comment] 2022-08-08 07:27
If it's urgent, As a quick workaround you can comment the code giving error. if you are not building a windows app it should work fine @FilledStacks 
![image](https://user-images.githubusercontent.com/90178033/183362802-8342eef5-cc45-4d76-8a86-5c775f096459.png)

**Comment by FilledStacks** [comment] 2022-08-08 07:31
> If it's urgent, As a quick workaround you can comment the code giving error. if you are not building a windows app it should work fine @FilledStacks ![image](https://user-images.githubusercontent.com/90178033/183362802-8342eef5-cc45-4d76-8a86-5c775f096459.png)

Thanks. This works locally. Not when I try and make a release to QA through our CI pipeline. I'll remove the package for now and add it back when this is fixed. 

Thanks for the response.

**Comment by sara010** [comment] 2022-08-08 07:56
same problem

**Comment by ryzizub** [comment] 2022-08-08 08:09
I temporary added overrides to pubspec.yaml, seems to work pretty well :) 
```
dependency_overrides:
  device_info_plus: '4.0.0'
  device_info_plus_platform_interface: '2.3.0+1'
```

**Comment by xrandy00** [comment] 2022-08-08 08:11
Since we specify the version of device_info_plus directly, I just added this
![image](https://user-images.githubusercontent.com/25846048/183371142-de3ecdf9-9784-4fd4-81d9-1f0869040893.png)

**Comment by ixre** [comment] 2022-08-08 09:25
edit file : [device_info_plus/lib/device_info_plus.dart](https://github.com/fluttercommunity/plus_plugins/blob/8b2f0496c8a7f952617fa24aec92e4e1b026c011/packages/device_info_plus/device_info_plus/lib/device_info_plus.dart) replace
 ```
Future<WindowsDeviceInfo> get windowsInfo async =>
      _cachedWindowsDeviceInfo ??= await _platform.windowsInfo()!;
```
to
```
Future<WindowsDeviceInfo> get windowsInfo async =>
      _cachedWindowsDeviceInfo !;
```
and edit file [device_info_plus_windows/lib/src/device_info_plus_windows.dart](https://github.com/fluttercommunity/plus_plugins/blob/055da8226efa54af42cd14600fef56c822209718/packages/device_info_plus/device_info_plus_windows/lib/src/device_info_plus_windows.dart) like this on line 25
```
 @override
  Future<WindowsDeviceInfo> windowsInfo() {
    return Future.value(null);
  }
```
now, i have avoid it temporarily.

**Comment by M123-dev** [comment] 2022-08-08 09:40
We had the same problem. After upgrading to `^4.0.2` it seems to be fixed.
Tests as well as local debug building works again

**Comment by miquelbeltran** [comment] 2022-08-10 05:05
Could you provide exact steps to reproduce the issue?

If I do the following, I can compile the app without issues:

    Create a flutter project
    add the device_info_plus dependency with flutter pub add device_info_plus
    Run the project on Android

All of that works.

**Comment by Stachuu87** [comment] 2022-08-10 05:24
In My case, i do not use device_info_plus itself, but it is a dependency for native_pdf_viewer which i import into my app (i use the lastest stable version of native_pdf_viewer).

Running flutter pup upgrade did not change anything in my case. Azure pipeline still fails with the same error.

**Comment by miquelbeltran** [comment] 2022-08-10 05:34
Thanks @Stachuu87 that helps.

I think the problem is that device_info_plus_platform_interface had a breaking change that was not provided inside a major version change. So apps depending on older versions of device_info_plus will break.

I will see if I can reproduce this issue and find a solution that doesn't break old clients.

**Comment by miquelbeltran** [comment] 2022-08-10 05:47
I have reverted the breaking change in device_info_plus_platform_interface and republished under:

```
device_info_plus_platform_interface    2.5.0
device_info_plus_windows               3.0.3
device_info_plus                       4.0.3
```

Please let me know if you still have the same issue

**Comment by Stachuu87** [comment] 2022-08-10 07:58
> I have reverted the breaking change in device_info_plus_platform_interface and republished under:
> 
> 
> 
> ```
> 
> device_info_plus_platform_interface    2.5.0
> 
> device_info_plus_windows               3.0.3
> 
> device_info_plus                       4.0.3
> 
> ```
> 
> 
> 
> Please let me know if you still have the same issue

It seems to work just fine from me.
Thanks for such a quick response.

**Comment by gOzaru** [comment] 2022-08-13 10:22
> I have reverted the breaking change in device_info_plus_platform_interface and republished under:
> 
> ```
> device_info_plus_platform_interface    2.5.0
> device_info_plus_windows               3.0.3
> device_info_plus                       4.0.3
> ```
> 
> Please let me know if you still have the same issue

@miquelbeltran 
It doesn't work in my case. 
It always gives error `(Null check operator used on a null value)`.
This is the code:
```dart
class Device extends GetxController {
  static final DeviceInfoPlugin deviceInfoPlugin = DeviceInfoPlugin();

  Future<Map<String, dynamic>> getDevice() async {
    Map<String, dynamic>? map;
    try {
      if (Platform.isAndroid) {
        map = _readAndroidBuildData(await deviceInfoPlugin.androidInfo);
      } else if (Platform.isIOS) {
        map = _readIosDeviceInfo(await deviceInfoPlugin.iosInfo);
      }
    } on PlatformException catch (e) {
      map = {
        "title": "Dart Package Failure",
        "message": e.toString(),
        "error": "Current dart package (device_info_plus) failed to get data.",
      };
      Get.offAll(() => AppError(title: map!['title'], message: map['message'], error: map['error']));
    }
    return map!;
  }

  Map<String, dynamic> _readAndroidBuildData(AndroidDeviceInfo build) {
    return <String, dynamic>{
      'version.securityPatch': build.version.securityPatch,
      'version.sdkInt': build.version.sdkInt,
      'version.release': build.version.release,
      'version.previewSdkInt': build.version.previewSdkInt,
      'version.incremental': build.version.incremental,
      'version.codename': build.version.codename,
      'version.baseOS': build.version.baseOS,
      'board': build.board,
      'bootloader': build.bootloader,
      'brand': build.brand,
      'device': build.device,
      'display': build.display,
      'fingerprint': build.fingerprint,
      'hardware': build.hardware,
      'host': build.host,
      'id': build.id,
      'manufacturer': build.manufacturer,
      'model': build.model,
      'product': build.product,
      'supported32BitAbis': build.supported32BitAbis,
      'supported64BitAbis': build.supported64BitAbis,
      'supportedAbis': build.supportedAbis,
      'tags': build.tags,
      'type': build.type,
      'isPhysicalDevice': build.isPhysicalDevice,
      'systemFeatures': build.systemFeatures,
    };
  }

  Map<String, dynamic> _readIosDeviceInfo(IosDeviceInfo data) {
    return <String, dynamic>{
      'name': data.name,
      'systemName': data.systemName,
      'systemVersion': data.systemVersion,
      'model': data.model,
      'localizedModel': data.localizedModel,
      'identifierForVendor': data.identifierForVendor,
      'isPhysicalDevice': data.isPhysicalDevice,
      'utsname.sysname:': data.utsname.sysname,
      'utsname.nodename:': data.utsname.nodename,
      'utsname.release:': data.utsname.release,
      'utsname.version:': data.utsname.version,
      'utsname.machine:': data.utsname.machine,
    };
  }
}
```

This is the pubspec.yaml:
```dart
dependencies:
  device_info_plus: 4.0.3
dependency_overrides:
  device_info_plus: 4.0.3
  device_info_plus_platform_interface: 2.5.0
```

![SS - Device Info Plus 4 0 3 on 2022-08-13 181934](https://user-images.githubusercontent.com/3258483/184479495-c4282e3e-07cf-42de-bb6c-7fb2b49f3020.jpg)

Is there something wrong with github?
Or dart pub.dev?

**Comment by miquelbeltran** [comment] 2022-08-14 08:19
> Thank you Flutter team.

No worries!

Just to be clear, we are NOT part of the Flutter Team/Google/etc. and we are not sponsored by them in any way (or at least, I am not, lol). These plugins are run by independent volunteers on our free time, so we need both help and patience from the rest of the community to be able to do so.

Since this issue seems to be solved, I am closing the ticket now. Please for any new issues check the existing open tickers or open a new ticket.

**Closed by miquelbeltran** 2022-08-14 08:19 UTC
Labels: bug, all, android, device_info_plus, windows
