### ISSUE TITLE
Issue with device_info_plus plugin causing compilation error on Codemagic

### ISSUE THREAD

**Issue by Ultranmus** [fluttercommunity/plus_plugins#2760] opened 2024-03-27 13:27 UTC
### What is your question?

I am encountering an issue with the device_info_plus plugin while building my Flutter app on Codemagic for Android. The error message I'm receiving is:

![image](https://github.com/fluttercommunity/plus_plugins/assets/140942235/b6a4c79f-7563-4322-bf98-85669b696966)

This issue does not occur when building the app locally, but it consistently arises during the Codemagic build process. I had experienced a similar problem locally before, but updating Android Studio resolved it for local builds. However, the issue persists on Codemagic.

Is there a way to resolve this problem?

### Checklist before submitting a question

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by miquelbeltran** [comment] 2024-03-27 15:43
I think the issue is that plugins require Java 17 from the last major version.

Have you contacted Codemagic about this? They should be able to provide a more up-to-date system image.

**Comment by Ultranmus** [comment] 2024-03-27 15:46
@miquelbeltran i did contacted them and currently trying to build with their solution.

**Comment by vbuberen** [comment] 2024-03-27 21:54
Java 17 is available on Codemagic for a long time already. You need to configure your workflow to use it.
By default Java 11 is picked on MacOS runners. 

Here, I mentioned how to do this change in another plugin: https://github.com/juliansteenbakker/mobile_scanner/issues/922#issuecomment-1914432008

Closing as not related to the plugin.

**Closed by vbuberen** 2024-03-27 21:54 UTC
Labels: question
