### ISSUE TITLE
text+images not sharing in instagram

### ISSUE THREAD

**Issue by NagariSai** [fluttercommunity/plus_plugins#711] opened 2022-01-25 08:03 UTC

**Comment by vbuberen** [comment] 2022-01-30 13:15
Please provide all the required information as it is described in the issue template. 

I suspect you have issues with Share Plus plugin. In such case please check https://github.com/fluttercommunity/plus_plugins/tree/main/packages/share_plus/share_plus#known-issues

**Comment by NagariSai** [comment] 2022-01-31 04:32
Hi,

This is my code .
I am using share_plus: ^3.0.4 plugin.
and sharing multiple images with text to instagram.
Images are sharing but text is not .

* imageList: List of image paths

  await Share.shareFiles(imageList,
           text: "sharetext with images",
           subject: "Sample",
           sharePositionOrigin: box.localToGlobal(Offset.zero) & 
box.size);

**Comment by miquelbeltran** [comment] 2022-01-31 08:26
Also please, use the bug template. Your bug doesn't follow the bug reporting template: https://github.com/fluttercommunity/plus_plugins/blob/main/.github/ISSUE_TEMPLATE/BUG.md

Please use the template or we will have to close this issue.

**Comment by miquelbeltran** [comment] 2022-02-01 13:28
From the share_plus readme: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/share_plus/share_plus

> Due to restrictions set up by Facebook this plugin isn't capable of sharing data reliably to Facebook related apps on Android and iOS. This includes eg. sharing text to the Facebook Messenger. If you require this functionality please check the native Facebook Sharing SDK (https://developers.facebook.com/docs/sharing) or search for other Flutter plugins implementing this SDK. More information can be found in this issue.

This is a problem that also exists on native code and is a limitation by the receiving app of the share action.

If you believe the issue is unrelated to this, please report a bug using the template and provide all the necessary information or we will close the issue.

**Comment by vbuberen** [comment] 2022-02-19 19:35
Looks like there will be no information. If the issue still exists open a new issue following provided templates.

**Closed by vbuberen** 2022-02-19 19:35 UTC
Labels: missing info
