### ISSUE TITLE
[Bug]: Not able to get Ip Address if network is connect to mobile data

### ISSUE THREAD

**Issue by khanjasir90** [fluttercommunity/plus_plugins#3321] opened 2024-10-16 07:19 UTC
### Platform

Iphone 13

### Plugin

network_info_plus

### Version

^4.0.1

### Flutter SDK

3.22.1

### Steps to reproduce

1. I am not able to get Ip address when connected to mobile data. it returns null

### Code Sample

```dart
final ip = await _network.getWifiIP();
print(ip) // null when connected to mobile data.
```

### Logs

```shell
None
```

### Flutter Doctor

```shell
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.1, on macOS 14.3 23D56 darwin-arm64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] VS Code (version 1.88.1)
```

### Checklist before submitting a bug

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by miquelbeltran** [comment] 2024-10-16 07:29
Not a bug, works as intended. The implementation uses `enumerateWifiAddresses` and the method is called `getWifiIP`.

There is already a feature request here: https://github.com/fluttercommunity/plus_plugins/issues/2036 so closing this one.

**Closed by miquelbeltran** 2024-10-16 07:29 UTC
Labels: bug, triage
