### ISSUE TITLE
[Bug]: share_plus Screen scrolling problem

### ISSUE THREAD

**Issue by mchtaktrk** [fluttercommunity/plus_plugins#2374] opened 2023-11-11 14:30 UTC
### Platform

Android 13

### Plugin

share_plus

### Version

7.2.1

### Flutter SDK

3.13.9

### Steps to reproduce

| ![ss1](https://github.com/fluttercommunity/plus_plugins/assets/9364520/ed6f7a62-1229-486f-9f8c-aab7f6af542f) | ![ss2](https://github.com/fluttercommunity/plus_plugins/assets/9364520/bd8b0a2c-0c80-4342-a5d0-1f82ea175844) | The screen scrolls up when the sharing screen is opened |
|:---:|:---:|:---:|

```yaml
dependencies:
 share_plus: ^7.2.1
```
```dart
import 'package:flutter/material.dart';
import 'package:share_plus/share_plus.dart';

class ScreenShareLink extends StatefulWidget {
  const ScreenShareLink({super.key});

  @override
  State<ScreenShareLink> createState() => _ScreenShareLinkState();
}

class _ScreenShareLinkState extends State<ScreenShareLink> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text("Share App"),
          backgroundColor: Colors.green.shade200,
        ),
        body: Center(
          child: IconButton(
              onPressed: () {
                Share.share('Hi!');
              },
              icon: Icon(Icons.share)),
        ));
  }
}
```

### Logs

```shell
[ +274 ms] ensureAnalyticsSent: 251ms
[        ] Running 0 shutdown hooks
[   +1 ms] Shutdown hooks complete
[        ] exiting with code 1
PS C:\Users\Asus\StudioProjects\istanbul_cicekleri> flutter run --verbose
[ +317 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[  +12 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[  +15 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +102 ms] executing: C:\Users\Asus\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[ +184 ms] List of devices attached
                    KJN7OBIFZXGQXCSG       device product:viva_global model:2201116TG device:viva transport_id:3
                    emulator-5554          device product:sdk_gphone_x86_64 model:sdk_gphone_x86_64 device:emu64xa transport_id:2
[  +22 ms] C:\Users\Asus\AppData\Local\Android\sdk\platform-tools\adb.exe -s KJN7OBIFZXGQXCSG shell getprop
[ +186 ms] C:\Users\Asus\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell getprop
[ +175 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[  +16 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +202 ms] Connected devices:
[   +4 ms] ro.hardware = mt6781
[        ] ro.build.characteristics = default
[   +1 ms] ro.hardware = ranchu
[   +4 ms] 2201116TG (mobile)         • KJN7OBIFZXGQXCSG • android-arm64 • Android 13 (API 33)
[   +4 ms] sdk gphone x86 64 (mobile) • emulator-5554    • android-x64   • Android 13 (API 33) (emulator)
[   +3 ms] [1]: 2201116TG (KJN7OBIFZXGQXCSG)
[   +1 ms] [2]: sdk gphone x86 64 (emulator-5554)
```

### Flutter Doctor

```shell
[√] Flutter (Channel stable, 3.13.9, on Microsoft Windows [Version 10.0.19045.3570], locale tr-TR)
    • Flutter version 3.13.9 on channel stable at D:\Projeler\flutter\flutter-sdk
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d211f42860 (2 weeks ago), 2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0

[√] Windows Version (Installed version of Windows is version 10 or higher)

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\Asus\AppData\Local\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.7.34031.279
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] VS Code (version 1.81.1)
    • VS Code at C:\Users\Asus\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (5 available)
    • 2201116TG (mobile)         • KJN7OBIFZXGQXCSG • android-arm64  • Android 13 (API 33)
    • sdk gphone x86 64 (mobile) • emulator-5554    • android-x64    • Android 13 (API 33) (emulator)
    • Windows (desktop)          • windows          • windows-x64    • Microsoft Windows [Version 10.0.19045.3570]
    • Chrome (web)               • chrome           • web-javascript • Google Chrome 119.0.6045.124
    • Edge (web)                 • edge             • web-javascript • Microsoft Edge 119.0.2151.44

[√] Network resources
    • All expected network resources are available.
```

### Checklist before submitting a bug

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment] 2023-11-16 23:16
This is duplicate of a few other issues we have: https://github.com/fluttercommunity/plus_plugins/issues/2143, https://github.com/fluttercommunity/plus_plugins/issues/1655
This issue happens only on some devices and not related to the plugin as plugin calls Android system share intent and doesn't render anything itself.

Please use search next time before opening an issue and putting a checkmark that you searched issues in the repository.

**Closed by vbuberen** 2023-11-16 23:16 UTC
Labels: bug, triage
