### ISSUE TITLE
[Bug]: android.permission.READ_PRIVILEGED_PHONE_STATE is required

### ISSUE THREAD

**Issue by Sevastyan** [fluttercommunity/plus_plugins#1986] opened 2023-07-27 12:17 UTC
### Platform

Android 11 (API 30)

### Plugin

device_info_plus

### Version

9.0.2

### Flutter SDK

3.0.1

### Steps to reproduce

1. Depend on some package that depends on `device_info_plus`, so that `device_info_plus` is your transitive dependency.
2. Go to `android` directory of the project.
3. Run `./gradlew build`.
4. Get the build error due to missing permission `android.permission.READ_PRIVILEGED_PHONE_STATE`.

### Logs

```shell
/home/droid/.pub-cache/hosted/pub.dev/device_info_plus-9.0.2/android/src/main/kotlin/dev/fluttercommunity/plus/device_info/MethodCallHandlerImpl.kt:84: Error: Missing permissions required by Build.getSerial: android.permission.READ_PRIVILEGED_PHONE_STATE [MissingPermission]
                    Build.getSerial()
                    ~~~~~~~~~~~~~~~~~

   Explanation for issues of type "MissingPermission":
   This check scans through your code and libraries and looks at the APIs
   being used, and checks this against the set of permissions required to
   access those APIs. If the code using those APIs is called at runtime, then
   the program will crash.

   Furthermore, for permissions that are revocable (with targetSdkVersion 23),
   client code must also be prepared to handle the calls throwing an exception
   if the user rejects the request for permission at runtime.
```

### Flutter Doctor

```shell
[✓] Flutter (Channel stable, 3.10.5, on Debian GNU/Linux 10 (buster) 4.19.0-24-amd64, locale en_US.UTF-8)
    • Flutter version 3.10.5 on channel stable at /home/droid/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (6 weeks ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /home/droid/Android/Sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • Java binary at: /home/droid/android_studio_new/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /opt/google/chrome/google-chrome-disabled-cors

[✓] Linux toolchain - develop for Linux desktop
    • clang version 7.0.1-8+deb10u2 (tags/RELEASE_701/final)
    • cmake version 3.13.4
    • ninja version 1.8.2
    • pkg-config version 0.29

[✓] Android Studio (version 2022.2)
    • Android Studio at /home/droid/android_studio_new/android-studio
    • Flutter plugin version 72.1.3
    • Dart plugin version 222.4560
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] Android Studio (version 2021.3)
    • Android Studio at /home/droid/android_studio
    • Flutter plugin version 69.0.3
    • Dart plugin version 213.7371
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at /home/droid/dev/soft/idea-IC-202.7660.26
    • Flutter plugin version 55.0.5
    • Dart plugin version 211.6693.108

[✓] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Linux (desktop)                    • linux         • linux-x64      • Debian GNU/Linux 10 (buster) 4.19.0-24-amd64
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 106.0.5249.119

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

### Checklist before submitting a bug

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment] 2023-07-29 18:08
I can't reproduce the issue when I am building the Flutter project with `flutter....` commands, but can do when trying to do as you describe even with direct dependency.
The problem is in lint used by default during Android builds. You can modify `lintOptions` in `build.gradle` file for your project to ignore this issue.
As this is part of Android lint configuration I wouldn't consider it a bug and will close the issue as Flutter projects build fine with proper commands.

Could you tell me the reason why do you need to build Android part this way?

**Closed by vbuberen** 2023-07-29 18:08 UTC
Labels: bug, triage

**Comment by Sevastyan** [comment] 2023-07-31 07:59
I'm developing a plugin for Flutter. I'm building android part via gradle commands since there is no code using the plugin from Flutter side yet.

How do I update `lintOptions`?

**Comment by vbuberen** [comment] 2023-08-01 07:20
> How do I update `lintOptions`?

You can modify your `build.gradle` file and add this part:

```
lintOptions {
      disable 'MissingPermission'
}
```

Here is an example on where to look for `lintOptions` in case they already present in your project or where to add the mentioned block in case you don't have any: https://github.com/fluttercommunity/plus_plugins/blob/42938c0c03132f7f50fa047c2970660d2720d320/packages/share_plus/share_plus/example/android/app/build.gradle#L37

Here is a more detailed guide on lint rules in Android for reference: https://developer.android.com/studio/write/lint

**Comment by marcotta** [comment] 2024-09-06 10:26
Sometimes it's useful to test if `./gradlew build` works, especially when importing new packages in the project and getting build failures.

@vbuberen Would you consider changing the plugin build.gradle from: 
```
lintOptions {
        disable 'InvalidPackage'
}
```

to:
```
lintOptions {
        disable 'InvalidPackage'
        disable 'MissingPermission'
}
```

I guess it would help other people who would otherwise spend time investigating the gradle linting errors.

Thanks a lot in advance
