### ISSUE TITLE
[Bug]: Thread 1: EXC_BAD_ACCESS (code=1, address=0x0)

### ISSUE THREAD

**Issue by phanvanluan94** [fluttercommunity/plus_plugins#2216] opened 2023-10-04 01:22 UTC
### Platform

iOS 16

### Plugin

connectivity_plus

### Version

4.0.2

### Flutter SDK

3.13.6

### Steps to reproduce

I got this crash issue when opening app on iOS 16.

![Screenshot 2023-10-04 at 08 14 48](https://github.com/fluttercommunity/plus_plugins/assets/22259333/535fa296-dda8-4e0f-a237-87b75de45462)
------
Note: It worked well on iOS 17

### Code Sample

```dart
reaction<ConnectivityResult?>((_) => connectivityStream.value, (result) {
   _isNoInternet = result == ConnectivityResult.none;
})
```

### Logs

```shell
2023-10-04 08:10:49.101196+0700 Runner[98845:7984311] Metal GPU Frame Capture Enabled
2023-10-04 08:10:49.101269+0700 Runner[98845:7984311] Metal API Validation Enabled
2023-10-04 08:10:49.135236+0700 Runner[98845:7984311] [VERBOSE-2:FlutterDarwinContextMetalImpeller.mm(37)] Using the Impeller rendering backend.
2023-10-04 08:10:49.140243+0700 Runner[98845:7984311] Warning: Unable to create restoration in progress marker file
2023-10-04 08:10:49.149366+0700 Runner[98845:7984311] <SKPaymentQueue: 0x2836f0080>: No observers found that respond to "paymentQueue:shouldAddStorePayment:forProduct:", will not check for purchase intents
2023-10-04 08:10:49.198220+0700 Runner[98845:7984646] 10.15.0 - [FirebaseAnalytics][I-ACS023007] Analytics v.10.15.0 started
2023-10-04 08:10:49.202261+0700 Runner[98845:7984646] 10.15.0 - [FirebaseAnalytics][I-ACS023008] To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
2023-10-04 08:10:49.202559+0700 Runner[98845:7984646] 10.15.0 - [FirebaseAnalytics][I-ACS025036] App Delegate Proxy is disabled
```

### Flutter Doctor

```shell
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.6, on macOS 14.0 23A344 darwin-arm64, locale
    en)
[✓] Android toolchain - develop for Android devices (Android SDK version
    34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.82.2)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!
luanphan@Luans-MacBook-Pro saigon-traffic-cam % flutter doctor -v
[✓] Flutter (Channel stable, 3.13.6, on macOS 14.0 23A344 darwin-arm64, locale
    en)
    • Flutter version 3.13.6 on channel stable at
      /Users/luanphan/ext_libs/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ead455963c (7 days ago), 2023-09-26 18:28:17 -0700
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version
    34.0.0)
    • Android SDK at /Users/luanphan/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.82.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.74.0

[✓] Connected device (4 available)
    • Nhi Iphone (3) (mobile)    • 00008110-000C51CE1E81401E            • ios
      • iOS 16.6.1 20G81
    • iPhone 15 Pro Max (mobile) • 2D0B6C91-2974-4B5E-8575-B9A3AFC34A9D • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-arm64   • macOS 14.0 23A344 darwin-arm64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 117.0.5938.132

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

### Checklist before submitting a bug

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment] 2023-10-04 05:46
It is already fixed and will be released later this week. The problem is in XCode 15, not the plugin 

https://github.com/fluttercommunity/plus_plugins/pull/2169

**Comment by phanvanluan94** [comment] 2023-10-04 10:31
> It is already fixed and will be released later this week. The problem is in XCode 15, not the plugin
> 
> #2169
It is really great, thank you!

**Comment by JooYoo** [comment] 2023-10-04 13:15
Also facing the same problem. I'm looking forward to see the new release.

**Comment by Marvioso** [comment] 2023-10-04 21:42
Same issue. Can you give a more accurate expected release time? The issue showed up in production for us since it doesn't affect ios simulators, and would hate to go through the process of removing the plugin from every file, just to have to put it back in a few days

**Comment by duythuong97** [comment] 2023-10-05 00:51
I tried to update Podfile to update IPHONEOS_DEPLOYMENT_TARGET to 12.0 and this issue was fixed. 

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
          xcconfig_path = config.base_configuration_reference.real_path
          xcconfig = File.read(xcconfig_path)
          xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
          File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }
      end
  end
  installer.pods_project.targets.each do |target|
      flutter_additional_ios_build_settings(target)
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end
  end
end
```

**Comment by vbuberen** [comment] 2023-10-05 02:10
> Can you give a more accurate expected release time? The issue showed up in production for us since it doesn't affect ios simulators, and would hate to go through the process of removing the plugin from every file, just to have to put it back in a few days
> 

Sure. As soon as I get paid for this work and customer support I will start providing more accurate release dates. But for now would be great if you could respect other people's time and priorities, especially since you can use the version pointing to the fix from main if you need that desperately.

**Comment by vbuberen** [comment] 2023-10-05 02:15
@duythuong97 Sorry, didn't mean to delete your comment. For me it showed twice, so I tried to delete the duplicate

**Comment by ChoyCheeWei** [comment] 2023-10-05 06:05
> > Can you give a more accurate expected release time? The issue showed up in production for us since it doesn't affect ios simulators, and would hate to go through the process of removing the plugin from every file, just to have to put it back in a few days
> 
> Sure. As soon as I get paid for this work and customer support I will start providing more accurate release dates. But for now would be great if you could respect other people's time and priorities, especially since you can use the version pointing to the fix from main if you need that desperately.

hi @vbuberen, is this how to point to the branch that has fixes for this?
 connectivity_plus:
    git:
      url: https://github.com/fluttercommunity/plus_plugins.git
      path: packages/connectivity_plus/connectivity_plus
      ref: main

**Comment by vbuberen** [comment] 2023-10-05 07:29
I would recommend pointing to exact commit with the fix instead of `main` branch to have reproducible environment and not worry about anything we continue merging into `main`.
```
connectivity_plus:
    git:
      url: https://github.com/fluttercommunity/plus_plugins.git
      path: packages/connectivity_plus/connectivity_plus
      ref: cf7d93fbfc76830acf2db755543cf4235a49df60
```

**Comment by vbuberen** [comment] 2023-10-09 08:44
The fix is released as part of `connectivity_plus: 5.0.0` version: https://pub.dev/packages/connectivity_plus/changelog#500

**Closed by vbuberen** 2023-10-09 08:44 UTC
Labels: bug, duplicate

**Comment by ephammer** [comment] 2023-10-16 14:49
I still see the error event on `connectivity_plus: 5.0.0`

**Comment by glintpursuit** [comment] 2023-10-27 05:39
@ephammer 

How did you resolve this?

We are unable to reproduce it locally, but App Store Connect crash analytics displays a huge number of crashes.

`Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Subtype: KERN_INVALID_ADDRESS at 0x0000000000000000
Exception Codes: 0x0000000000000001, 0x0000000000000000
VM Region Info: 0 is not in any region.  Bytes before following region: 4309909504
      REGION TYPE                 START - END      [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                   100e40000-100e48000 [   32K] r-x/r-x SM=COW  ...er.app/Runner
Termination Reason: SIGNAL 11 Segmentation fault: 11
Terminating Process: exc handler [4210]

Triggered by Thread:  0`

**Comment by ephammer** [comment] 2023-10-27 08:32
@glintpursuit I did not the problem is still there

**Comment by vbuberen** [comment] 2023-10-27 08:38
It means that you have something wrong in your iOS config.
Check out here for a similar case
https://github.com/fluttercommunity/plus_plugins/issues/2276

**Comment by glintpursuit** [comment] 2023-10-27 12:30
@ephammer 

Thanks to [Marián Hlaváč comment here](https://github.com/fluttercommunity/plus_plugins/issues/2276#issuecomment-1773056178)

We have successfully fixed the issue. It was quite challenging, as we encountered more than 300 crashes in just two days 😢. Unfortunately, Crashlytics didn’t detect any of these crashes.

Previously, I was explicitly setting the IPHONEOS_DEPLOYMENT_TARGET to 11. However, after making some necessary updates, we have managed to resolve the issue.

`post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
         end
    end
  end`

**Comment by ephammer** [comment] 2023-10-29 12:06
> @ephammer
> 
> Thanks to [Marián Hlaváč comment here](https://github.com/fluttercommunity/plus_plugins/issues/2276#issuecomment-1773056178)
> 
> We have successfully fixed the issue. It was quite challenging, as we encountered more than 300 crashes in just two days 😢. Unfortunately, Crashlytics didn’t detect any of these crashes.
> 
> Previously, I was explicitly setting the IPHONEOS_DEPLOYMENT_TARGET to 11. However, after making some necessary updates, we have managed to resolve the issue.
> 
> `post_install do |installer| installer.generated_projects.each do |project| project.targets.each do |target| target.build_configurations.each do |config| config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0' end end end`

This worked, thank you very much
