### ISSUE TITLE
[connectivity_plus] Getting release build error

### ISSUE THREAD

**Issue by sureace** [fluttercommunity/plus_plugins#98] opened 2021-01-28 04:47 UTC
I am getting release build error when i use connectivity_plus plugin. Other than this is working very well.
Error
-----
[+31703 ms] [+31728 ms] Unexpected object (Class with illegal cid, full-aot):
0x1152a01d1 Library:'package:win32/src/kernel32.dart' Class: ::
[   +4 ms] [   +6 ms] Dart snapshot generator failed with exit code -6
[ +292 ms] [ +259 ms] Unexpected object (Class with illegal cid, full-aot):
0x1164879e1 Library:'package:win32/src/kernel32.dart' Class: ::
[        ] [        ] Dart snapshot generator failed with exit code -6
[ +199 ms] [ +195 ms] Unexpected object (Class with illegal cid, full-aot):
0x1114079e1 Library:'package:win32/src/kernel32.dart' Class: ::
[   +1 ms] [        ] Dart snapshot generator failed with exit code -6
[        ] [  +20 ms] Target android_aot_release_android-arm failed: Exception:
AOT snapshotter exited with code -6
[        ]            #0      AndroidAot.build
(package:flutter_tools/src/build_system/targets/android.dart:260:7)
[        ]            <asynchronous suspension>
[        ]            #1      _BuildInstance._invokeInternal
(package:flutter_tools/src/build_system/build_system.dart:801:27)
[        ]            #2      _rootRunUnary (dart:async/zone.dart:1198:47)
[        ]            #3      _CustomZone.runUnary
(dart:async/zone.dart:1100:19)
[        ]            #4      _FutureListener.handleValue
(dart:async/future_impl.dart:143:18)
[        ]            #5      Future._propagateToListeners.handleValueCallback
(dart:async/future_impl.dart:696:45)
[        ]            #6      Future._propagateToListeners
(dart:async/future_impl.dart:725:32)
[        ]            #7      Future._completeWithValue
(dart:async/future_impl.dart:529:5)
[        ]            #8      _AsyncAwaitCompleter.complete
(dart:async-patch/async_patch.dart:40:15)
[        ]            #9      _completeOnAsyncReturn
(dart:async-patch/async_patch.dart:311:13)
[        ]            #10     Node.computeChanges
(package:flutter_tools/src/build_system/build_system.dart)
[        ]            #11     _rootRunUnary (dart:async/zone.dart:1198:47)
[        ]            #12     _CustomZone.runUnary
(dart:async/zone.dart:1100:19)
[        ]            #13     _FutureListener.handleValue
(dart:async/future_impl.dart:143:18)
[        ]            #14     Future._propagateToListeners.handleValueCallback
(dart:async/future_impl.dart:696:45)
[        ]            #15     Future._propagateToListeners
(dart:async/future_impl.dart:725:32)
[        ]            #16     Future._completeWithValue
(dart:async/future_impl.dart:529:5)
[   +1 ms]            #17     _AsyncAwaitCompleter.complete
(dart:async-patch/async_patch.dart:40:15)
[        ]            #18     _completeOnAsyncReturn
(dart:async-patch/async_patch.dart:311:13)
[        ]            #19     FileStore.diffFileList
(package:flutter_tools/src/build_system/file_store.dart)
[        ]            #20     _rootRunUnary (dart:async/zone.dart:1198:47)
[        ]            #21     _CustomZone.runUnary
(dart:async/zone.dart:1100:19)
[        ]            #22     _FutureListener.handleValue
(dart:async/future_impl.dart:143:18)
[        ]            #23     Future._propagateToListeners.handleValueCallback
(dart:async/future_impl.dart:696:45)
[        ]            #24     Future._propagateToListeners
(dart:async/future_impl.dart:725:32)
[        ]            #25     Future._completeWithValue
(dart:async/future_impl.dart:529:5)
[        ]            #26     Future.wait.<anonymous closure>
(dart:async/future.dart:414:23)
[        ]            #27     _rootRunUnary (dart:async/zone.dart:1198:47)
[        ]            #28     _CustomZone.runUnary
(dart:async/zone.dart:1100:19)
[        ]            #29     _FutureListener.handleValue
(dart:async/future_impl.dart:143:18)
[        ]            #30     Future._propagateToListeners.handleValueCallback
(dart:async/future_impl.dart:696:45)
[        ]            #31     Future._propagateToListeners
(dart:async/future_impl.dart:725:32)
[        ]            #32     Future._completeWithValue
(dart:async/future_impl.dart:529:5)
[        ]            #33     _AsyncAwaitCompleter.complete
(dart:async-patch/async_patch.dart:40:15)
[        ]            #34     _completeOnAsyncReturn
(dart:async-patch/async_patch.dart:311:13)
[        ]            #35     FileStore._hashFile
(package:flutter_tools/src/build_system/file_store.dart)
[        ]            #36     _rootRunUnary (dart:async/zone.dart:1198:47)
[        ]            #37     _CustomZone.runUnary
(dart:async/zone.dart:1100:19)
[        ]            #38     _FutureListener.handleValue
(dart:async/future_impl.dart:143:18)
[        ]            #39     Future._propagateToListeners.handleValueCallback
(dart:async/future_impl.dart:696:45)
[        ]            #40     Future._propagateToListeners
(dart:async/future_impl.dart:725:32)
[        ]            #41     Future._completeWithValue
(dart:async/future_impl.dart:529:5)
[        ]            #42     Future._asyncCompleteWithValue.<anonymous closure>
(dart:async/future_impl.dart:567:7)
[        ]            #43     _rootRun (dart:async/zone.dart:1190:13)
[        ]            #44     _CustomZone.run (dart:async/zone.dart:1093:19)
[        ]            #45     _CustomZone.runGuarded
(dart:async/zone.dart:997:7)
[        ]            #46     _CustomZone.bindCallbackGuarded.<anonymous
closure> (dart:async/zone.dart:1037:23)
[        ]            #47     _microtaskLoop
(dart:async/schedule_microtask.dart:41:21)
[        ]            #48     _startMicrotaskLoop
(dart:async/schedule_microtask.dart:50:5)
[        ]            #49     _runPendingImmediateCallback
(dart:isolate-patch/isolate_patch.dart:118:13)
[        ]            #50     _RawReceivePortImpl._handleMessage
(dart:isolate-patch/isolate_patch.dart:169:5)
[        ] [   +1 ms] Target android_aot_release_android-arm64 failed:
Exception: AOT snapshotter exited with code -6
[        ]            #0      AndroidAot.build
(package:flutter_tools/src/build_system/targets/android.dart:260:7)
[        ]            <asynchronous suspension>
[        ]            #1      _BuildInstance._invokeInternal
(package:flutter_tools/src/build_system/build_system.dart:801:27)
[        ]            #2      _rootRunUnary (dart:async/zone.dart:1198:47)
[        ]            #3      _CustomZone.runUnary
(dart:async/zone.dart:1100:19)
[        ]            #4      _FutureListener.handleValue
(dart:async/future_impl.dart:143:18)
[        ]            #5      Future._propagateToListeners.handleValueCallback
(dart:async/future_impl.dart:696:45)
[        ]            #6      Future._propagateToListeners
(dart:async/future_impl.dart:725:32)
[        ]            #7      Future._completeWithValue
(dart:async/future_impl.dart:529:5)
[        ]            #8      _AsyncAwaitCompleter.complete
(dart:async-patch/async_patch.dart:40:15)
[        ]            #9      _completeOnAsyncReturn
(dart:async-patch/async_patch.dart:311:13)
[        ]            #10     Node.computeChanges
(package:flutter_tools/src/build_system/build_system.dart)
[        ]            #11     _rootRunUnary (dart:async/zone.dart:1198:47)
[        ]            #12     _CustomZone.runUnary
(dart:async/zone.dart:1100:19)
[        ]            #13     _FutureListener.handleValue
(dart:async/future_impl.dart:143:18)
[        ]            #14     Future._propagateToListeners.handleValueCallback
(dart:async/future_impl.dart:696:45)
[        ]            #15     Future._propagateToListeners
(dart:async/future_impl.dart:725:32)
[        ]            #16     Future._completeWithValue
(dart:async/future_impl.dart:529:5)
[        ]            #17     _AsyncAwaitCompleter.complete
(dart:async-patch/async_patch.dart:40:15)
[        ]            #18     _completeOnAsyncReturn
(dart:async-patch/async_patch.dart:311:13)
[        ]            #19     FileStore.diffFileList
(package:flutter_tools/src/build_system/file_store.dart)
[        ]            #20     _rootRunUnary (dart:async/zone.dart:1198:47)
[        ]            #21     _CustomZone.runUnary
(dart:async/zone.dart:1100:19)
[        ]            #22     _FutureListener.handleValue
(dart:async/future_impl.dart:143:18)
[        ]            #23     Future._propagateToListeners.handleValueCallback
(dart:async/future_impl.dart:696:45)
[        ]            #24     Future._propagateToListeners
(dart:async/future_impl.dart:725:32)
[        ]            #25     Future._completeWithValue
(dart:async/future_impl.dart:529:5)
[        ]            #26     Future.wait.<anonymous closure>
(dart:async/future.dart:414:23)
[        ]            #27     _rootRunUnary (dart:async/zone.dart:1198:47)
[        ]            #28     _CustomZone.runUnary
(dart:async/zone.dart:1100:19)
[        ]            #29     _FutureListener.handleValue
(dart:async/future_impl.dart:143:18)
[        ]            #30     Future._propagateToListeners.handleValueCallback
(dart:async/future_impl.dart:696:45)
[        ]            #31     Future._propagateToListeners
(dart:async/future_impl.dart:725:32)
[        ]            #32     Future._completeWithValue
(dart:async/future_impl.dart:529:5)
[        ]            #33     _AsyncAwaitCompleter.complete
(dart:async-patch/async_patch.dart:40:15)
[        ]            #34     _completeOnAsyncReturn
(dart:async-patch/async_patch.dart:311:13)
[   +1 ms]            #35     FileStore._hashFile
(package:flutter_tools/src/build_system/file_store.dart)
[   +1 ms]            #36     _rootRunUnary (dart:async/zone.dart:1198:47)
[        ]            #37     _CustomZone.runUnary
(dart:async/zone.dart:1100:19)
[        ]            #38     _FutureListener.handleValue
(dart:async/future_impl.dart:143:18)
[        ]            #39     Future._propagateToListeners.handleValueCallback
(dart:async/future_impl.dart:696:45)
[        ]            #40     Future._propagateToListeners
(dart:async/future_impl.dart:725:32)
[        ]            #41     Future._completeWithValue
(dart:async/future_impl.dart:529:5)
[        ]            #42     Future._asyncCompleteWithValue.<anonymous closure>
(dart:async/future_impl.dart:567:7)
[        ]            #43     _rootRun (dart:async/zone.dart:1190:13)
[        ]            #44     _CustomZone.run (dart:async/zone.dart:1093:19)
[        ]            #45     _CustomZone.runGuarded
(dart:async/zone.dart:997:7)
[        ]            #46     _CustomZone.bindCallbackGuarded.<anonymous
closure> (dart:async/zone.dart:1037:23)
[        ]            #47     _microtaskLoop
(dart:async/schedule_microtask.dart:41:21)
[        ]            #48     _startMicrotaskLoop
(dart:async/schedule_microtask.dart:50:5)
[        ]            #49     _runPendingImmediateCallback
(dart:isolate-patch/isolate_patch.dart:118:13)
[        ]            #50     _RawReceivePortImpl._handleMessage
(dart:isolate-patch/isolate_patch.dart:169:5)
[        ] [   +1 ms] Target android_aot_release_android-x64 failed: Exception:
AOT snapshotter exited with code -6
[        ]            #0      AndroidAot.build
(package:flutter_tools/src/build_system/targets/android.dart:260:7)
[        ]            <asynchronous suspension>
[        ]            #1      _BuildInstance._invokeInternal
(package:flutter_tools/src/build_system/build_system.dart:801:27)
[        ]            #2      _rootRunUnary (dart:async/zone.dart:1198:47)
[        ]            #3      _CustomZone.runUnary
(dart:async/zone.dart:1100:19)
[        ]            #4      _FutureListener.handleValue
(dart:async/future_impl.dart:143:18)
[        ]            #5      Future._propagateToListeners.handleValueCallback
(dart:async/future_impl.dart:696:45)
[        ]            #6      Future._propagateToListeners
(dart:async/future_impl.dart:725:32)
[        ]            #7      Future._completeWithValue
(dart:async/future_impl.dart:529:5)
[        ]            #8      _AsyncAwaitCompleter.complete
(dart:async-patch/async_patch.dart:40:15)
[        ]            #9      _completeOnAsyncReturn
(dart:async-patch/async_patch.dart:311:13)
[        ]            #10     Node.computeChanges
(package:flutter_tools/src/build_system/build_system.dart)
[        ]            #11     _rootRunUnary (dart:async/zone.dart:1198:47)
[        ]            #12     _CustomZone.runUnary
(dart:async/zone.dart:1100:19)
[        ]            #13     _FutureListener.handleValue
(dart:async/future_impl.dart:143:18)
[        ]            #14     Future._propagateToListeners.handleValueCallback
(dart:async/future_impl.dart:696:45)
[        ]            #15     Future._propagateToListeners
(dart:async/future_impl.dart:725:32)
[        ]            #16     Future._completeWithValue
(dart:async/future_impl.dart:529:5)
[        ]            #17     _AsyncAwaitCompleter.complete
(dart:async-patch/async_patch.dart:40:15)
[        ]            #18     _completeOnAsyncReturn
(dart:async-patch/async_patch.dart:311:13)
[   +1 ms]            #19     FileStore.diffFileList
(package:flutter_tools/src/build_system/file_store.dart)
[   +1 ms]            #20     _rootRunUnary (dart:async/zone.dart:1198:47)
[   +3 ms]            #21     _CustomZone.runUnary
(dart:async/zone.dart:1100:19)
[        ]            #22     _FutureListener.handleValue
(dart:async/future_impl.dart:143:18)
[        ]            #23     Future._propagateToListeners.handleValueCallback
(dart:async/future_impl.dart:696:45)
[        ]            #24     Future._propagateToListeners
(dart:async/future_impl.dart:725:32)
[        ]            #25     Future._completeWithValue
(dart:async/future_impl.dart:529:5)
[        ]            #26     Future.wait.<anonymous closure>
(dart:async/future.dart:414:23)
[        ]            #27     _rootRunUnary (dart:async/zone.dart:1198:47)
[        ]            #28     _CustomZone.runUnary
(dart:async/zone.dart:1100:19)
[        ]            #29     _FutureListener.handleValue
(dart:async/future_impl.dart:143:18)
[        ]            #30     Future._propagateToListeners.handleValueCallback
(dart:async/future_impl.dart:696:45)
[   +1 ms]            #31     Future._propagateToListeners
(dart:async/future_impl.dart:725:32)
[   +5 ms]            #32     Future._completeWithValue
(dart:async/future_impl.dart:529:5)
[   +1 ms]            #33     _AsyncAwaitCompleter.complete
(dart:async-patch/async_patch.dart:40:15)
[        ]            #34     _completeOnAsyncReturn
(dart:async-patch/async_patch.dart:311:13)
[   +8 ms]            #35     FileStore._hashFile
(package:flutter_tools/src/build_system/file_store.dart)
[   +1 ms]            #36     _rootRunUnary (dart:async/zone.dart:1198:47)
[   +2 ms]            #37     _CustomZone.runUnary
(dart:async/zone.dart:1100:19)
[   +2 ms]            #38     _FutureListener.handleValue
(dart:async/future_impl.dart:143:18)
[   +1 ms]            #39     Future._propagateToListeners.handleValueCallback
(dart:async/future_impl.dart:696:45)
[   +1 ms]            #40     Future._propagateToListeners
(dart:async/future_impl.dart:725:32)
[   +1 ms]            #41     Future._completeWithValue
(dart:async/future_impl.dart:529:5)
[   +2 ms]            #42     Future._asyncCompleteWithValue.<anonymous closure>
(dart:async/future_impl.dart:567:7)
[   +5 ms]            #43     _rootRun (dart:async/zone.dart:1190:13)
[        ]            #44     _CustomZone.run (dart:async/zone.dart:1093:19)
[        ]            #45     _CustomZone.runGuarded
(dart:async/zone.dart:997:7)
[        ]            #46     _CustomZone.bindCallbackGuarded.<anonymous
closure> (dart:async/zone.dart:1037:23)
[        ]            #47     _microtaskLoop
(dart:async/schedule_microtask.dart:41:21)
[        ]            #48     _startMicrotaskLoop
(dart:async/schedule_microtask.dart:50:5)
[        ]            #49     _runPendingImmediateCallback
(dart:isolate-patch/isolate_patch.dart:118:13)
[        ]            #50     _RawReceivePortImpl._handleMessage
(dart:isolate-patch/isolate_patch.dart:169:5)
[   +2 ms] [  +14 ms] 
[        ]            #0      throwToolExit
(package:flutter_tools/src/base/common.dart:14:3)
[   +1 ms]            #1      AssembleCommand.runCommand
(package:flutter_tools/src/commands/assemble.dart:238:7)
[   +1 ms]            #2      _rootRunUnary (dart:async/zone.dart:1198:47)
[   +1 ms]            #3      _CustomZone.runUnary
(dart:async/zone.dart:1100:19)
[        ]            #4      _FutureListener.handleValue
(dart:async/future_impl.dart:143:18)
[   +1 ms]            #5      Future._propagateToListeners.handleValueCallback
(dart:async/future_impl.dart:696:45)
[   +1 ms]            #6      Future._propagateToListeners
(dart:async/future_impl.dart:725:32)
[   +1 ms]            #7      Future._completeWithValue
(dart:async/future_impl.dart:529:5)
[   +1 ms]            #8      _AsyncAwaitCompleter.complete
(dart:async-patch/async_patch.dart:40:15)
[   +1 ms]            #9      _completeOnAsyncReturn
(dart:async-patch/async_patch.dart:311:13)
[   +1 ms]            #10     FlutterBuildSystem.build
(package:flutter_tools/src/build_system/build_system.dart)
[   +5 ms]            #11     _rootRunUnary (dart:async/zone.dart:1198:47)
[   +1 ms]            #12     _CustomZone.runUnary
(dart:async/zone.dart:1100:19)
[        ]            #13     _FutureListener.handleValue
(dart:async/future_impl.dart:143:18)
[        ]            #14     Future._propagateToListeners.handleValueCallback
(dart:async/future_impl.dart:696:45)
[        ]            #15     Future._propagateToListeners
(dart:async/future_impl.dart:725:32)
[        ]            #16     Future._completeWithValue
(dart:async/future_impl.dart:529:5)
[   +1 ms]            #17     _AsyncAwaitCompleter.complete
(dart:async-patch/async_patch.dart:40:15)
[   +1 ms]            #18     _completeOnAsyncReturn
(dart:async-patch/async_patch.dart:311:13)
[        ]            #19     _BuildInstance.invokeTarget
(package:flutter_tools/src/build_system/build_system.dart)
[        ]            #20     _rootRunUnary (dart:async/zone.dart:1198:47)
[        ]            #21     _CustomZone.runUnary
(dart:async/zone.dart:1100:19)
[        ]            #22     _FutureListener.handleValue
(dart:async/future_impl.dart:143:18)
[        ]            #23     Future._propagateToListeners.handleValueCallback
(dart:async/future_impl.dart:696:45)
[        ]            #24     Future._propagateToListeners
(dart:async/future_impl.dart:725:32)
[        ]            #25     Future._completeWithValue
(dart:async/future_impl.dart:529:5)
[   +1 ms]            #26     Future.wait.<anonymous closure>
(dart:async/future.dart:414:23)
[        ]            #27     _rootRunUnary (dart:async/zone.dart:1198:47)
[   +1 ms]            #28     _CustomZone.runUnary
(dart:async/zone.dart:1100:19)
[        ]            #29     _FutureListener.handleValue
(dart:async/future_impl.dart:143:18)
[   +6 ms]            #30     Future._propagateToListeners.handleValueCallback
(dart:async/future_impl.dart:696:45)
[        ]            #31     Future._propagateToListeners
(dart:async/future_impl.dart:725:32)
[        ]            #32     Future._completeWithValue
(dart:async/future_impl.dart:529:5)
[        ]            #33     _AsyncAwaitCompleter.complete
(dart:async-patch/async_patch.dart:40:15)
[        ]            #34     _completeOnAsyncReturn
(dart:async-patch/async_patch.dart:311:13)
[   +1 ms]            #35     _BuildInstance.invokeTarget
(package:flutter_tools/src/build_system/build_system.dart)
[   +1 ms]            #36     _rootRunUnary (dart:async/zone.dart:1198:47)
[   +1 ms]            #37     _CustomZone.runUnary
(dart:async/zone.dart:1100:19)
[        ]            #38     _FutureListener.handleValue
(dart:async/future_impl.dart:143:18)
[        ]            #39     Future._propagateToListeners.handleValueCallback
(dart:async/future_impl.dart:696:45)
[   +1 ms]            #40     Future._propagateToListeners
(dart:async/future_impl.dart:725:32)
[   +6 ms]            #41     Future._completeWithValue
(dart:async/future_impl.dart:529:5)
[   +2 ms]            #42     Future.wait.<anonymous closure>
(dart:async/future.dart:414:23)
[   +2 ms]            #43     _rootRunUnary (dart:async/zone.dart:1198:47)
[        ]            #44     _CustomZone.runUnary
(dart:async/zone.dart:1100:19)
[        ]            #45     _FutureListener.handleValue
(dart:async/future_impl.dart:143:18)
[   +1 ms]            #46     Future._propagateToListeners.handleValueCallback
(dart:async/future_impl.dart:696:45)
[        ]            #47     Future._propagateToListeners
(dart:async/future_impl.dart:725:32)
[        ]            #48     Future._completeWithValue
(dart:async/future_impl.dart:529:5)
[        ]            #49     _AsyncAwaitCompleter.complete
(dart:async-patch/async_patch.dart:40:15)
[        ]            #50     _completeOnAsyncReturn
(dart:async-patch/async_patch.dart:311:13)
[        ]            #51     _BuildInstance._invokeInternal
(package:flutter_tools/src/build_system/build_system.dart)
[        ]            #52     _asyncErrorWrapperHelper.errorCallback
(dart:async-patch/async_patch.dart:91:64)
[        ]            #53     _rootRunBinary (dart:async/zone.dart:1214:47)
[        ]            #54     _CustomZone.runBinary
(dart:async/zone.dart:1107:19)
[        ]            #55     _FutureListener.handleError
(dart:async/future_impl.dart:157:20)
[        ]            #56     Future._propagateToListeners.handleError
(dart:async/future_impl.dart:708:47)
[        ]            #57     Future._propagateToListeners
(dart:async/future_impl.dart:729:24)
[   +1 ms]            #58     Future._completeError
(dart:async/future_impl.dart:537:5)
[        ]            #59     _AsyncAwaitCompleter.completeError
(dart:async-patch/async_patch.dart:47:15)
[        ]            #60     AndroidAot.build
(package:flutter_tools/src/build_system/targets/android.dart)
[        ]            #61     _rootRunUnary (dart:async/zone.dart:1198:47)
[        ]            #62     _CustomZone.runUnary
(dart:async/zone.dart:1100:19)
[   +4 ms]            #63     _FutureListener.handleValue
(dart:async/future_impl.dart:143:18)
[        ]            #64     Future._propagateToListeners.handleValueCallback
(dart:async/future_impl.dart:696:45)
[        ]            #65     Future._propagateToListeners
(dart:async/future_impl.dart:725:32)
[        ]            #66     Future._completeWithValue
(dart:async/future_impl.dart:529:5)
[        ]            #67     _AsyncAwaitCompleter.complete
(dart:async-patch/async_patch.dart:40:15)
[        ]            #68     _completeOnAsyncReturn
(dart:async-patch/async_patch.dart:311:13)
[        ]            #69     AOTSnapshotter.build
(package:flutter_tools/src/base/build.dart)
[        ]            #70     _rootRunUnary (dart:async/zone.dart:1198:47)
[        ]            #71     _CustomZone.runUnary
(dart:async/zone.dart:1100:19)
[        ]            #72     _FutureListener.handleValue
(dart:async/future_impl.dart:143:18)
[        ]            #73     Future._propagateToListeners.handleValueCallback
(dart:async/future_impl.dart:696:45)
[        ]            #74     Future._propagateToListeners
(dart:async/future_impl.dart:725:32)
[        ]            #75     Future._completeWithValue
(dart:async/future_impl.dart:529:5)
[        ]            #76     _AsyncAwaitCompleter.complete
(dart:async-patch/async_patch.dart:40:15)
[        ]            #77     _completeOnAsyncReturn
(dart:async-patch/async_patch.dart:311:13)
[        ]            #78     _DefaultProcessUtils.stream
(package:flutter_tools/src/base/process.dart)
[        ]            #79     _rootRunUnary (dart:async/zone.dart:1198:47)
[        ]            #80     _CustomZone.runUnary
(dart:async/zone.dart:1100:19)
[        ]            #81     _FutureListener.handleValue
(dart:async/future_impl.dart:143:18)
[        ]            #82     Future._propagateToListeners.handleValueCallback
(dart:async/future_impl.dart:696:45)
[        ]            #83     Future._propagateToListeners
(dart:async/future_impl.dart:725:32)
[        ]            #84     Future._completeWithValue
(dart:async/future_impl.dart:529:5)
[        ]            #85     Future._asyncCompleteWithValue.<anonymous closure>
(dart:async/future_impl.dart:567:7)
[        ]            #86     _rootRun (dart:async/zone.dart:1190:13)
[        ]            #87     _CustomZone.run (dart:async/zone.dart:1093:19)
[        ]            #88     _CustomZone.runGuarded
(dart:async/zone.dart:997:7)
[        ]            #89     _CustomZone.bindCallbackGuarded.<anonymous
closure> (dart:async/zone.dart:1037:23)
[        ]            #90     _microtaskLoop
(dart:async/schedule_microtask.dart:41:21)
[        ]            #91     _startMicrotaskLoop
(dart:async/schedule_microtask.dart:50:5)
[        ]            #92     _runPendingImmediateCallback
(dart:isolate-patch/isolate_patch.dart:118:13)
[        ]            #93     _RawReceivePortImpl._handleMessage
(dart:isolate-patch/isolate_patch.dart:169:5)
[        ] FAILURE: Build failed with an exception.
[        ] * Where:
[        ] Script
'/Users/xxxxxxxx/flutter/packages/flutter_tools/gradle/flutter.gradle'
line: 904
[        ] * What went wrong:
[        ] Execution failed for task ':app:compileFlutterBuildRelease'.
[        ] > Process 'command '/Users/xxxxxxx/flutter/bin/flutter''
finished with non-zero exit value 1
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info
or --debug option to get more log output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 1m 27s

Flutter doctor
---------------
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.4 19E287 darwin-x64,
    locale en)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.52.1)
[✓] Connected device (1 available)

• No issues found!

Gradle
--------
distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.2-all.zip
classpath 'com.android.tools.build:gradle:3.5.4'
classpath 'com.google.gms:google-services:4.3.4'

Thank you

**Comment by miquelbeltran** [comment] 2021-01-28 07:42
Hi @sureace can you please provide reproduction steps and hopefully a link to a small project that reproduces the error? Also, which version of Android are you using?

**Comment by sureace** [comment] 2021-01-28 07:52
Hi @miquelbeltran i follow the release apk or appbundle build as per the flutter. Without connectivity_plus plugin i am able to generate appbundle or apk successfully. 

Pubspec.yaml
---------------
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  device_preview: ^0.5.5
  #connectivity_plus: ^0.7.1 #build issue, but development it is working as expected.
  #connectivity: ^2.0.2 #working, but listener is not working
  cross_connectivity: ^2.0.1 #working, but delay in status listener
  flutter_bloc: ^6.1.1
  equatable: ^1.2.5
  firebase_core: ^0.7.0
  firebase_auth: ^0.20.0
  cloud_firestore: ^0.16.0
  cloud_functions: ^0.9.0
  google_sign_in: ^4.5.9
  firebase_storage: ^7.0.0
  firebase_messaging: ^8.0.0-dev.7
  google_fonts: ^1.1.1
  meta: ^1.2.4
  sign_in_with_apple: ^2.5.4
  pin_code_fields: ^6.0.2
  sms_autofill: ^1.2.7
  bot_toast: ^3.0.5
  image_picker: ^0.6.7+21
  image_cropper: ^1.3.1
  sqflite: ^1.3.2+2
  rxdart: ^0.25.0
  introduction_screen: ^1.0.9
  dots_indicator: ^1.2.0
  qr_code_scanner: ^0.3.0
  mqtt_client: ^8.1.0
  flutter_slidable: ^0.5.7
  wifi: ^0.1.5
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
  fonts:
    - family: Helvetica
      fonts:
        - asset: assets/fonts/Helvetica-Light.ttf
        - asset: assets/fonts/Helvetica-LightOblique.ttf
          style: italic
        - asset: assets/fonts/Helvetica-Bold.ttf
          weight: 700

Android version
----------------
minSdkVersion 20
targetSdkVersion 29
ext.kotlin_version = '1.3.50'

Thanks
Suresh

**Comment by viveky259259** [comment] 2021-01-31 09:53
@sureace I was able to generate android release app with following packages

 mobx: ^1.2.1
  flutter_mobx: ^1.1.0
  flutter_modular: ^2.0.1
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  path_provider: ^1.6.10
  cached_network_image:
  device_preview: ^0.5.5
    #connectivity_plus: ^0.7.1 #build issue, but development it is working as expected.
    #connectivity: ^2.0.2 #working, but listener is not working
  cross_connectivity: ^2.0.1 #working, but delay in status listener
  connectivity_plus: ^0.7.1
  flutter_bloc: ^6.1.1
  equatable: ^1.2.5
  firebase_core: ^0.7.0
  firebase_auth: ^0.20.0
  cloud_firestore: ^0.16.0
  cloud_functions: ^0.9.0
  google_sign_in: ^4.5.9
  firebase_storage: ^7.0.0
  firebase_messaging: ^8.0.0-dev.7
  google_fonts: ^1.1.1
  meta: ^1.2.4
  sign_in_with_apple: ^2.5.4
  pin_code_fields: ^6.0.2
  sms_autofill: ^1.2.7
  bot_toast: ^3.0.5
  image_picker: ^0.6.7+21
  image_cropper: ^1.3.1
  sqflite: ^1.3.2+2
  rxdart: ^0.25.0
  introduction_screen: ^1.0.9
  dots_indicator: ^1.2.0
  qr_code_scanner: ^0.3.0
  mqtt_client: ^8.1.0
  flutter_slidable: ^0.5.7
  wifi: ^0.1.5


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0


Can you check why are you getting error?

**Comment by mhadaily** [comment] 2021-07-16 13:57
Please upgrade to the latest version and try again.

If everything works, please close this PR. otherwise, let us know.

**Comment by mhadaily** [comment] 2021-08-18 18:03
Close due to new version releases and inactivity. Feel free to reopen if you still have an issue.

**Closed by mhadaily** 2021-08-18 18:03 UTC
Labels: bug, connectivity_plus

**Comment by paramaggarwal** [comment] 2022-07-05 14:06
This is the problem: https://github.com/fluttercommunity/plus_plugins/commit/7b2e11b13478af78cc9a4c9300e0772cd70812d2#r77734987
